### ISSUE TITLE
Solid Colored Cards on Timeline Page Affecting UI 

### ISSUE THREAD

**Issue by diwakarchaurasiya** [vansh-codes/ChaosWeb#100]
### Description:
The solid-colored cards on the timeline page make the user interface appear outdated and unprofessional, lacking modern design appeal.

### Proposed Solution:
Implement a glassmorphic effect for the cards to give them a sleek, modern, and transparent look. This will enhance the visual aesthetics while maintaining readability and user engagement.GIve me a chance to show my css skills and make ui look stunning.

### From
![Screenshot 2024-10-13 143319](https://github.com/user-attachments/assets/1dc8aa64-5052-4840-8e02-2a6d064a282b)

### TO

![Screenshot 2024-10-13 143637](https://github.com/user-attachments/assets/d3aa971d-e5db-4e40-bdbf-d66f07f0f647)

**Comment by vansh-codes** [comment]
Looks good! Go ahead

**Comment by diwakarchaurasiya** [comment]
thanks for assigning me this issue please assign a level to it.

**Comment by vansh-codes** [comment]
levels will be assigned after on your PR seeing your work and complexity of the work

**Comment by diwakarchaurasiya** [comment]
thanks for your kind response.

**Comment by diwakarchaurasiya** [comment]
I have created this by changing background image and cards bg color and intractions , tell me if it is looking good or suggest me about some of your brand color or theme.

https://github.com/user-attachments/assets/4cf4fd87-df4c-48fc-be92-dcfc05a76faf

**Comment by vansh-codes** [comment]
Good! If its done then you can create PR

**Comment by diwakarchaurasiya** [comment]
thanks vansh for your kind words ,it was a great journey of building a tech and finding bugs in it and fixing it,It was full of learning and insight.

Looking forward to contribute more ,
