### ISSUE TITLE
Documentation Chaos: LICENSE Link in Readme file is not set

### ISSUE THREAD

**Issue by heizshubham** [vansh-codes/ChaosWeb#101]
### Describe the Documentation Update

I wanna add MIT LICENSE Link in the Readme file,  for better look.

### Add References or Examples

<img width="924" alt="image" src="https://github.com/user-attachments/assets/c4acf5b7-66be-45f6-8cfc-3b860852caef">

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead but I can't give you any level labels for this

**Comment by heizshubham** [comment]
I have push the changes in pr please merge it.

**Comment by vansh-codes** [comment]
Completed
