### ISSUE TITLE
Chaotic Feat: About us page is empty

### ISSUE THREAD

**Issue by Jay-1409** [vansh-codes/ChaosWeb#103]
### Describe your chaotic idea

I am back with another chaotic idea. 
I had an idea for the About us page:
- Can we have all the contributer profile pic floating around in the page?

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/62faa90d-f713-4077-be70-d11db77df407) \
something like this ?

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Good idea, create new Contributors page and do it there
You gonna do it in React right?

**Comment by Jay-1409** [comment]
> Good idea, create new Contributors page and do it there You gonna do it in React right?

Yup in react. It might take some time thanks!!

**Comment by vansh-codes** [comment]
Completed
