### ISSUE TITLE
Chaotic Feat: Proposal to Add Horror-Themed Features (Jump Scares & Creepy Cursor)

### ISSUE THREAD

**Issue by sumitkumar9128** [vansh-codes/ChaosWeb#105]
### Describe your chaotic idea

Hi,

I hope you're doing well! I’d like to propose adding two exciting, horror-themed features to the ChaosWeb project that align with its chaotic and unconventional nature.

1. **Jump Scares:**
I plan to introduce random jump scares triggered when hovering over specific elements like buttons, sliders, images. These will be spooky images that appear briefly on the screen, adding to the chaotic and eerie atmosphere.

2. **Creepy Cursor:**
This feature will change the default cursor to a creepy hand (or other eerie icon) to enhance the overall unsettling experience while navigating the site.

**Merge Conflict Assurance:**
To ensure a smooth integration, I will work on these features in a separate branch, making sure the changes are isolated to new assets (images) and minor, non-disruptive additions to existing JavaScript and CSS files. This will prevent any merge conflicts with ongoing or future work on the main branch.

Please let me know your thoughts! I’m excited to contribute and make the project even more delightfully chaotic. 😈

Please add all labels which rely under hacktoberfest and gssoc-ext 2024 with level 3.
please...

### Add Screenshots or Sketches

Not now, when i am done i'll share you screenrecord

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
We have a React version in `chaosweb-v@2` folder, you will be implementing this in React right??

**Comment by sumitkumar9128** [comment]
Okay @vansh-codes i will take care of everything. please assign level as well

**Comment by vansh-codes** [comment]
After PR if I feel it deserves level3 so I wil upgrade

**Comment by sumitkumar9128** [comment]
Yes, I’ll be implementing both features in the React version (chaosweb-v@2). I’ll only need to make some minor addition/modification.
Everything will fit smoothly with the current setup, and I’ll make sure there are no merge conflicts.


okay @vansh-codes atleast assign me officially.
