### ISSUE TITLE
Chaotic Feat:Add a  chaotic review  section

### ISSUE THREAD

**Issue by sayanp607** [vansh-codes/ChaosWeb#106]
### Describe your chaotic idea

In the review section, user can give their reviews and also check others reviews. But surely, these all tasks will be done in a chaotic environment. I have already contributed  in your project, so I am well known to your moto with this project. Please assign this task to me, I will complete it sure. 

### Add Screenshots or Sketches

![review  choas](https://github.com/user-attachments/assets/6ecb710f-f50d-4fe7-bbe6-9649a547a994)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
We dont have any backend to get these reviews! So how will this work or will it be only for show purpose?

**Comment by sayanp607** [comment]
> We dont have any backend to get these reviews! So how will this work or will it be only for show purpose?

Yes, as there is no backend, it will be only for show purpose, some hard coded reviews will be shown there in the slider mode , specially it will be chaotic!

**Comment by vansh-codes** [comment]
okay then go ahead! Please try not to have a vertical scollbar, the main motive of website was not to have a vertical scrollbar but may contributors failed to do it, hoping you will do it correctly

**Comment by vansh-codes** [comment]
You will be doing this in React folder right?
- `chaosweb-v@2` folder for React

**Comment by sayanp607** [comment]
> You will be doing this in React folder right?
> 
> * `chaosweb-v@2` folder for React

Yes brother, and Thank You again for assigning me.
