### ISSUE TITLE
Chaotic Feat: Add a "Do a Barrel Roll" Button

### ISSUE THREAD

**Issue by Yash8077** [vansh-codes/ChaosWeb#108]
### Describe your chaotic idea

I propose adding a playful "Do a Barrel Roll" button to the website's interface. This button would trigger a fun, visually appealing animation, perhaps rotating the entire page or the contents of a specific element.
### Add Screenshots or Sketches

![aO6a_Q](https://github.com/user-attachments/assets/af434f4b-e01e-4649-92ca-2f8358241e82)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by Yash8077** [comment]
![aO6a_Q](https://github.com/user-attachments/assets/af434f4b-e01e-4649-92ca-2f8358241e82)

**Comment by Sourabh782** [comment]
@vansh-codes is this issue free? if yes i would like to contribute to this task :))

**Comment by Yash8077** [comment]
Hi I am working on it! I'll soon make a PR.

**Comment by vansh-codes** [comment]
Whats the update @Yash8077 ??

**Comment by Yash8077** [comment]
> Whats the update @Yash8077 ??

Made a PR regarding this.
