### ISSUE TITLE
Chaotic Feat:Bouncing Div Like DVD Logo Effect

### ISSUE THREAD

**Issue by Yash8077** [vansh-codes/ChaosWeb#109]
### Describe your chaotic idea

Implement a bouncing <div> element on the page that mimics the classic DVD logo effect, where the div continuously moves around the screen, bouncing off the edges of the window. The div should change direction upon hitting any edge, and for an extra chaotic twist, the div could change color every time it hits a wall. This div will continue to bounce indefinitely while the user interacts with the page.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/0b3d6248-4857-40ed-b7de-2491585b4b37)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Chaotic idea! Go ahead!
Implement this in React version present in `chaosweb-v@2` folder

**Comment by RachitSahu26** [comment]
assign me i am going to work on this

**Comment by Yash8077** [comment]
> assign me i am going to work on this

I am working on it already buddy.

**Comment by RachitSahu26** [comment]
@Yash8077 hey when you can not resolve the issue over the 1 week so why did you take it ,Because of people like you, how can I contribute ? You just take it and it takes a lot of time due to which the one who does it quickly gets his/her turn closed.

**Comment by Yash8077** [comment]
Instead of being accusatory and poaching others issue, I would suggest you to find unique issues and think of some new ideas.
