### ISSUE TITLE
CHAOS REPORT:Addition of Navbar including login signup and a logo

### ISSUE THREAD

**Issue by Prachiikhar25** [vansh-codes/ChaosWeb#11]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

For definitive and more precise page 
any web page must have a navbar 
I'll do a good job making navbar, keeping color palate in mind just fitting as you would like!
feel free to make changes. 

![{094109FF-A9D9-4675-ADB9-FE2B85008155}](https://github.com/user-attachments/assets/cc042041-64d6-4186-8343-afca854f1796)

I'll be using this palate

![{CFC123EE-A655-4446-A02E-1743F24D5D4F}](https://github.com/user-attachments/assets/f5f02ee3-48b7-491b-80e0-d56247eaac9f)

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
It already exists #2 
Sorry for this time, but you can search for another new issues 
Keep up the chaos!
Happy Coding🚀
