### ISSUE TITLE
Chaotic Feat: Chaotic Maze game

### ISSUE THREAD

**Issue by bhaviya18** [vansh-codes/ChaosWeb#111]
### Describe your chaotic idea

I want to add a chaotic maze game

### Add Screenshots or Sketches

![Screenshot_20241014_135758_Chrome](https://github.com/user-attachments/assets/7db5e63a-f034-4616-9823-8a515914132b)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Its already there in the html version Check [here](https://vansh-codes.github.io/ChaosWeb/maze.html)
But i would like you to do it in react version as well similar to the image you shared, it should be chaotic, the controls should not be revealed, the controls should be random everytime and there should be a starting and ending point of the game
For any questions, feel free to leave a comment tagging me
