### ISSUE TITLE
Chaotic Feat: Add an invert color button 

### ISSUE THREAD

**Issue by bhaviya18** [vansh-codes/ChaosWeb#112]
### Describe your chaotic idea

I want to add an invert color button on the website

### Add Screenshots or Sketches

![Screenshot_20241014_140539_Chrome](https://github.com/user-attachments/assets/73675ccb-7fce-45fb-b5a9-613b3d0f2bfe)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Please exlain more about your idea and whats the image you have shared??

**Comment by bhaviya18** [comment]
@vansh-codes the photo is  just to showcase the inverted colors. Just like a dark mode button my idea is to add an invert colors button which will basically invert all the colors.

**Comment by vansh-codes** [comment]
Ohh okay got it!
Can you write efficient code for this in react?
What I am expecting is:
just like dark and light mode we specify css as
```
.dark .header{
something
}```

like this for dark mode so I want similar for invert so everyone can do it while contributing, it should be as follows:
```
.invert .classname or #idname
{
css styling
}

so on inverting, .invert class should be applied everywhere

Can you do it this way??

**Comment by bhaviya18** [comment]
I can try. But can I do this in html, css. I am not pro efficient in react yet.

**Comment by vansh-codes** [comment]
we have already shifted in react so thats why I was asking to do in React

**Comment by bhaviya18** [comment]
@vansh-codes  Okay I can do it in React. Please assign me.

**Comment by vansh-codes** [comment]
You are assigned 🚀

**Comment by bhaviya18** [comment]
@vansh-codes  Thank you! I am working on it. Can you kindly add level label as well.

**Comment by vansh-codes** [comment]
I will add on PR depending on the complexity and your work

**Comment by vansh-codes** [comment]
for now I am adding level2 label, it may change seeing your contribution
