### ISSUE TITLE
CHAOS REPORT: The webpage is not responsive on mobile and any other view except laptop

### ISSUE THREAD

**Issue by srivishnu2805** [vansh-codes/ChaosWeb#113]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

The webpage is not responsive on mobile and any other view except on a laptop so the words or letters are missing at some places make it dirty to read
![image](https://github.com/user-attachments/assets/be332a79-a1a5-4529-8c56-0a88fff41c2a)

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

Please assign me to work on this issue to make the webpage responsive in any mode of device compactable

**Comment by vansh-codes** [comment]
you will make full wesbite responsive or only the front page??

**Comment by vansh-codes** [comment]
Go ahead!

**Comment by srivishnu2805** [comment]
@vansh-codes  As there are huge animations and effects on the front and Timeline page I am unable to add CSS and the existing CSS is also not allowing responsiveness to the pages. The other 5 pages or files were made responsive and alignments were properly given for their best look some other bugs were also resolved like irregular page height in Contact Us and blank area in Contact Us, which has been removed successfully.

**Comment by vansh-codes** [comment]
No area, do it on whatever possible
