### ISSUE TITLE
Chaotic Feat: **HIGH PRIORITY** Switch to TailwindCSSS

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/ChaosWeb#114]
### Describe your chaotic idea

I would like to add tailwindcss to the project's react version for easier styling and responsivity
Whoever can change the full website from css to tailwindcss will be rewarded level3 but on one condition
- the appearance should be either the same or better then its now!

### Add Screenshots or Sketches

N/A

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by ArpitaAgrahari** [comment]
I would like to work on this. Can you please assign it to me.

**Comment by vansh-codes** [comment]
Assigning to you @ArpitaAgrahari 
Hoping to see the UI either same or better in tailwind ✨

**Comment by anchalchaturvedi08** [comment]
Hello PA, I want to work on this issue. Can you assign it to me?

**Comment by vansh-codes** [comment]
@ArpitaAgrahari any updates? Are you working on it?

**Comment by vansh-codes** [comment]
??

**Comment by vansh-codes** [comment]
⁉️❓⁉️❓🤔

**Comment by vansh-codes** [comment]
@ArpitaAgrahari ❓
