### ISSUE TITLE
Chaotic Feat: Time-Based Auto-Redirect Feature

### ISSUE THREAD

**Issue by hamzathul** [vansh-codes/ChaosWeb#118]
### Describe your chaotic idea

I would like to contribute a Time-Based Auto-Redirect feature that automatically redirects users between different pages at regular intervals in the app (e.g., every 15 seconds). This will add a layer of chaotic unpredictability as users will be constantly bounced between different pages, creating a disorienting but playful experience.

### Add Screenshots or Sketches

Functionality: When a user is on a page, they will be automatically redirected to another page after 15 seconds. This redirect will keep happening cyclically between multiple pages (or between two pages).

Use Case: It creates chaos by not allowing users to settle on a single page. As soon as they start interacting with one page, they will be taken to another, introducing a sense of unpredictability and loss of control.

Customization: The interval can be adjusted to different time frames (e.g., 10 seconds, 30 seconds) based on the level of chaos desired.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
You are assigned! Chaotic idea 🚀 
Note:
- set the interval to be 30seconds

**Comment by vansh-codes** [comment]
Do it in react folder `chaosweb-v@2`
