### ISSUE TITLE
Documentation Chaos: Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by LitZeus** [vansh-codes/ChaosWeb#12]
### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
#13 is also the same
Do both the tasks in this issue and close #13 as its same so it doesnt needs two different issues
Keep up the chaos!
