### ISSUE TITLE
Chaotic Feat: Create a New Section for Chaotic Games: "Chaos Mania"

### ISSUE THREAD

**Issue by Tamanna225** [vansh-codes/ChaosWeb#120]
### Describe your chaotic idea

I want to create a dedicated section on the website called "Chaos Mania" to host all the chaotic, interactive games in one place. Currently, the chaotic features and games are mixed together, which leads to confusion and clutter. The name of the website is Chaos but Chaos should not hamper user experience it should elevate it. If the user won't even know what we offer they won't stay on our website.

Features:
-want to create a new page/section named "Chaos Mania" where all chaotic games will be placed.
-The section will include:
        -A list or grid of chaotic games, for each game.
        -Direct access for users to play and interact with these games from this section.
-new chaotic games to be added directly to this section in the future, keeping the games organized.
-Existing chaotic games to be moved into "Chaos Mania" like Maze Game
- Also there are a lot of Chaotic buttons in ChaosWeb so can add a game in Chaos Mania for this , adding all the Chaotic Buttons in a Section name OUR BUTTONS COLLECTION which will have all the chaotic buttons and any further chaotic buttons can be added in this section only.

### Add Screenshots or Sketches

N/A

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Do it in React folder `chaosweb-v@2`
