### ISSUE TITLE
Chaotic Feat:Want to  improvement the look of website

### ISSUE THREAD

**Issue by Dipanita45** [vansh-codes/ChaosWeb#122]
### Describe your chaotic idea

Add more Css features to make eye catching and user friendly

### Add Screenshots or Sketches

![Uploading Screenshot 2024-10-15 122849.png…]()
![Screenshot 2024-10-15 221113](https://github.com/user-attachments/assets/ecb58ff5-543b-4561-8d9f-2af71b3b4081)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Image not available, please reupload the image

**Comment by Dipanita45** [comment]
Uploaded the images @vansh-codes

**Comment by vansh-codes** [comment]
What changes are done? What new you added?

**Comment by Dipanita45** [comment]
Improve the home page

**Comment by vansh-codes** [comment]
What improvement thats what I am asking, what improvements will you be doing and how?

**Comment by Dipanita45** [comment]
I will improve the colour constrast and readability of the website

**Comment by vansh-codes** [comment]
Please explain detail @Dipanita45 or else I have to close the issue as I dont find it needful

**Comment by arpit74170** [comment]
Assign this task to me, i have understand your concern that you want better user view and some catching css uses..
i will gonna fix this issue by adding hover effects and some box shadow over the cards with a better color

**Comment by Dipanita45** [comment]
I will use css properties like adding transition, font colour, background
colour contrast to the homepage and other page whenever required for better
readability to the user
