### ISSUE TITLE
Chaotic Feat: Wants to add new simon game 

### ISSUE THREAD

**Issue by Bhumika-00** [vansh-codes/ChaosWeb#130]
### Describe your chaotic idea

It will be a game of your memory test using colours.That page will be in a chaotic vibrant colours theme.

### Add Screenshots or Sketches

![IMG_20241015_195321](https://github.com/user-attachments/assets/abce7e9d-2785-4b7b-af7e-43ca70c0508e)
This is the idea 

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
I am allowing this time, from next time this wont be allowed, you first have to create issue and wait till its assigned

**Comment by Bhumika-00** [comment]
Okay thanks

**Comment by Bhumika-00** [comment]
Do you want any more changes??

**Comment by Bhumika-00** [comment]
game.mp4
<https://drive.google.com/file/d/1NbGKv8elt10rnMt-WSEGnxZ5zucAxb97/view?usp=drivesdk>
Please review it than I will apply for pr request

**Comment by vansh-codes** [comment]
Cool! Create a PR
