### ISSUE TITLE
Chaotic Feat: Adding a new section named "Emoji-Land"

### ISSUE THREAD

**Issue by anshika-1102** [vansh-codes/ChaosWeb#132]
### Describe your chaotic idea

- Emoji-Land is a chaotic digital playground where a variety of chaotic emojis float across the screen, growing and shrinking randomly. 
- The emojis react to your movements, expanding dramatically when you hover over them
- Each emoji plays its own unique, glitchy sound effect, creating an irritating atmosphere.
- The background flashes through various shades of grey, adding a sense of visual chaos.

### Add Screenshots or Sketches

![Screenshot 2024-10-14 184438](https://github.com/user-attachments/assets/9614fb99-5ab2-4913-beac-ec7926a51817)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!
