### ISSUE TITLE
Chaotic Feat:  Scroll bar of your website is not looking good and not suiting on your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [vansh-codes/ChaosWeb#133]
### Describe your chaotic idea

Chaotic Feat:  Scroll bar of your website is not looking good and not suiting on your website.

### Add Screenshots or Sketches

![barscroll](https://github.com/user-attachments/assets/85d85853-8aa5-4ea3-b35d-9fa9e453932a)

https://github.com/user-attachments/assets/13942714-80d5-4269-8884-6c83b4f45566

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by arpit74170** [comment]
pls Assign this task to me , i will add the scroll bar which have better ui and better experience

**Comment by vansh-codes** [comment]
You will do this in the React website right?

**Comment by arpit74170** [comment]
Yes if you say ,i can do it

**Comment by VinayLodhi1712** [comment]
@vansh-codes yes but assign this issue to me with gssoc extended and hactoberfest labels and also add level in it.

**Comment by VinayLodhi1712** [comment]
bro i have created this issue so this issue should assigned to me

**Comment by vansh-codes** [comment]
Yes Vinay it will be assigned to you! Will you do this task in React? @VinayLodhi1712

**Comment by VinayLodhi1712** [comment]
@vansh-codes yes sir! plz assign with labels and levels.
