### ISSUE TITLE
Chaotic Feat:  choatic footer addition 

### ISSUE THREAD

**Issue by RiyaJain8114** [vansh-codes/ChaosWeb#134]
### Describe your chaotic idea

Request for Footer Implementation
I propose adding an experimental, non-traditional footer that aligns with the overall chaotic user interface concept.

Proposal:
Floating Links: Instead of static links, important page links (like Privacy Policy, Terms of Service) could hover, shift, or randomly change positions on hover.
Randomized Social Media Icons: Social media icons could appear with randomized shapes or animations, moving sporadically across the screen.

### Add Screenshots or Sketches

na 

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by protham02** [comment]
Please assign this task to me.

**Comment by vansh-codes** [comment]
This issue already exists and is been worked upon
Check #6
Closing this issue
