### ISSUE TITLE
ADD Dedicated page for github  contributors 

### ISSUE THREAD

**Issue by shubhagarwal1** [vansh-codes/ChaosWeb#137]

**Comment by vansh-codes** [comment]
Please provide more details and your ideas on how will you make it chaotic

**Comment by shubhagarwal1** [comment]
hey @vansh-codes i will add a dedicated page for github contributors 
sorting them in order of the contributions the one has made to the repo 
the page would look likethis 
![Screenshot 2024-10-19 at 6 04 07 PM](https://github.com/user-attachments/assets/23bdb068-9058-4e57-a283-0799d91046ef)
hey @vansh-codes please assign me this task

**Comment by vansh-codes** [comment]
How will you make this chaotic ??
Please read the readme once, we want everything visually appealing as well as chaotic

**Comment by shubhagarwal1** [comment]
> How will you make this chaotic ?? Please read the readme once, we want everything visually appealing as well as chaotic

i will try to keep it minilistic following the best design practices, ihave mentioned a sample in issue description

**Comment by vansh-codes** [comment]
Have you gone through the readme and the purpose of the website? 
It has to be something chaotic, something odd
How will you make it chaotic/odd?

**Comment by shubhagarwal1** [comment]
@vansh-codes i really want to know you thoughts about the implmentation desgin
do you have somethign specific in you mind, i will try to make it that way and add some flavour of mine too..

**Comment by vansh-codes** [comment]
Do whatever you like 😅

**Comment by shubhagarwal1** [comment]
> Do whatever you like 😅

Hey @vansh-codes please assign me this task, then only i can work on it, accordin to rules
hope you understand.
