### ISSUE TITLE
Chaotic Feat: Add animations to input text in Contact page

### ISSUE THREAD

**Issue by KhawajaFashi** [vansh-codes/ChaosWeb#14]
### Describe your chaotic idea

I would like to add dangling/chaotic animation animation to the input text of contact form.

### Add Screenshots or Sketches

N/A

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
You can start working on it as soon as #2 is completed and merge! 

Keep up the chaos 😵‍💫
Happy Coding 🚀
Show you love and ⭐ the repository!

**Comment by vansh-codes** [comment]
Are you working on this??

**Comment by KhawajaFashi** [comment]
> Are you working on this??

I am sorry sir I was busy I will start working on it but I cannot guarantee that I will be able to do it or not because I don't have much experience with js as I am a new developer. Right now I have an idea to store the input text in an array and apply animation to every character. Let me know what you think. If I am not able to do it I will let u know in 2 to 3 days.

**Comment by vansh-codes** [comment]
Okay try it!

**Comment by coding-geek-nm** [comment]
i would like to contribute
