### ISSUE TITLE
Chaotic Feat: Add Translation Tool

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vansh-codes/ChaosWeb#141]
### Describe your chaotic idea

I want to add a Translation Tool(all language) properly.

@vansh-codes  PA please assign me this task.

### Add Screenshots or Sketches

![Screenshot 2024-10-18 222108](https://github.com/user-attachments/assets/f263408a-5cc4-4b27-bced-92d88e306112)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Its not required in this @Subhajit-2023-44 
Closing the issue
