### ISSUE TITLE
Adding the Title and Logo of "Chaos" in the platform title.

### ISSUE THREAD

**Issue by MuKulsoop** [vansh-codes/ChaosWeb#144]
### Describe your chaotic idea

There is still Vite+React showing in the title of the platform. It has to be changed to maintain the beauty of the platform.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/f3f06c9b-2712-489e-ba1d-13834531c7b2)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by MuKulsoop** [comment]
Can I work on this issue @vansh-codes

**Comment by vansh-codes** [comment]
GO ahead!

**Comment by muskiagrwal** [comment]
can you please assign me this issue , i want to work on it
