### ISSUE TITLE
CHAOS REPORT: once we go back to the homepage after any other page, the cards do not fall out

### ISSUE THREAD

**Issue by avogadroB** [vansh-codes/ChaosWeb#146]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

![image](https://github.com/user-attachments/assets/1a72530f-fd33-46e0-9a22-1e0e87c7e134)
The cards are unclickable and we need to reload the website to go anywhere again.

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Hoping you will fix this issue, Go ahead!

**Comment by pbln** [comment]
Is the problem solved or can still be tried ? Actually I faced the same issue .

**Comment by avogadroB** [comment]
okay so i tried putting on back buttons and creating a pull request for it. I got 1 error during vercel deployment and I am trying to debug it. Could you help me finding the header file (as in which subfolder it belongs to) ? I am getting a broken link as there are 2 versions of the app (the current version is in v2 subfolder). Thanks!

**Comment by vansh-codes** [comment]
![image](https://github.com/user-attachments/assets/6f24a616-9802-4f06-a872-d8c8fdc1ce67)

@avogadroB

**Comment by avogadroB** [comment]
I needed to change a few file names for vite+react to work from VS code. The main.jsx needs to be renamed to index.js. and I made a few directory changes as well for it to run using npm start
