### ISSUE TITLE
Add table to contents to the readme file

### ISSUE THREAD

**Issue by T-Fathima** [vansh-codes/ChaosWeb#147]
### Describe the Documentation Update

I would like to add table of contents sections to the readme file for better readability and enhanced user experience.

@vansh-codes Please asign this this to me.
I would like to work on it.

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
The readme is already short and its not required!
Sorry for this time
Closing this issue
