### ISSUE TITLE
Add Support for Greeting Messages via greeting.yaml

### ISSUE THREAD

**Issue by ananyag309** [vansh-codes/ChaosWeb#158]
### Describe your chaotic idea

Implement a greeting.yaml configuration file to handle customizable greeting messages for users. This file will allow project maintainers or contributors to easily define and update greeting messages for various use cases such as:

Welcoming new contributors.
Providing project-specific instructions.
Offering guidance for first-time users or visitors.

### Add Screenshots or Sketches

none

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!
