### ISSUE TITLE
Connect Four Game

### ISSUE THREAD

**Issue by samriddhitiwary** [vansh-codes/ChaosWeb#159]
### Describe your chaotic idea

The Connect Four game in ReactJS features a 7x6 grid where two players take turns dropping colored discs. The game alternates turns, checks for winning conditions (four in a row horizontally, vertically, or diagonally), and detects draws when the board is full. Players can restart the game with a button, and the responsive design ensures it's playable on various devices. The game utilizes React components to manage the state and render the game board dynamically.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/d3840456-f73e-4241-ac20-2df0e7531944)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!

**Comment by samriddhitiwary** [comment]
@vansh-codes Thank you I will start working on it

**Comment by vansh-codes** [comment]
Completed
