### ISSUE TITLE
CHAOS REPORT: Fixing Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [vansh-codes/ChaosWeb#160]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

Currently, the website's preloader functionality is not functioning as expected. The preloader, a visual element designed to indicate loading progress, is not appearing on the website, leaving users with a blank screen until the page fully loads. This can lead to a negative user experience, especially on slower connections.

@vansh-codes can you assign this issue to me with labels "gssoc-ext" with levels 3 and "hacktoberfest-accepted";

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
There already exists a preloader in https://vansh-codes.github.io/ChaosWeb
Create similar preloader in React version https://chaosweb.vercel.app

**Comment by VidhanThakur09** [comment]
Thank you for assigning this issue to me. I will convert the preloader into React.
