### ISSUE TITLE
CHAOS REPORT: The Directory system of the chaosweb-v@2 is unorganised, making it hard to work with and impossible to reroute to other pages after clicking on a card

### ISSUE THREAD

**Issue by avogadroB** [vansh-codes/ChaosWeb#169]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

Hi I am debugging issue #146 and it is taking a while to sort out due to random folders and unkept references in the webpages. It works fine if you just go from homepage->any other page, but does not work if you go back. This also creates the problem of accessing .mp3 and .jpeg in assets. If you are okay, I would like to reorganise all the pages and create a proper routing path for the directories. It would take a day or 2 but it will be done.

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead! I hope you will take care and work under folder structure rules and good practices
If not done correctly then I might ask you to change again and again

**Comment by vansh-codes** [comment]
Assigning level1 for now, but if you do good work then I might upgrade to level2

**Comment by avogadroB** [comment]
For context, the website works fine if you are going forward ie home-> timelines, etc. but the problem is when you go back, it gives a runtime error on vscode for multiple files.

**Comment by vansh-codes** [comment]
We have to fix errors that come up

**Comment by vansh-codes** [comment]
cant move forward having errors

**Comment by vansh-codes** [comment]
Can you explain the issues sharing some screenshots?
Also please once more explain that what does your issue says, what is the meaning of your issue, maybe I am confused
