### ISSUE TITLE
Chaotic Feat:  Improve style of testing page

### ISSUE THREAD

**Issue by Mr-DK07** [vansh-codes/ChaosWeb#17]
### Describe your chaotic idea

Hey @vansh-codes I want to recreate the design of home page. It should more interactive for user.
This can improve the UI/UX of the website.

### Add Screenshots or Sketches

Currently it is looking so simple and not much attractive. 

![Screenshot 2024-10-07 182206](https://github.com/user-attachments/assets/aa75f739-a1ab-4282-b740-7702dd933b9e)

Could you assign this task to me, so that I can start working on it.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Wait for #2 to be completed and merged, then if required I will ping you then you can improve the UI
Till that time, search for new issues or explore
https://github.com/vansh-codes/Gityzer

**Comment by vansh-codes** [comment]
You can check the setup now and propose your idea for changes so we can proceed further 🚀

**Comment by Mr-DK07** [comment]
Hey @vansh-codes I am proposed to recreate the design of this testing page. I simply wanted to make the UI better. I wanted to add a attractive background and change the design of existing element like button, Text etc.
I can add some animation also, which is good for the website.

currently this is looks like very simple and not much attractive.
![Screenshot 2024-10-07 182206](https://github.com/user-attachments/assets/f6963853-e1bf-4093-bfa1-be6bb3f56f77)

**Comment by vansh-codes** [comment]
Do check the deployment again, its already updated and changed
- check the new UI and then propose me your ideas for modification

**Comment by vansh-codes** [comment]
Check the deployment brother, if you have already forked then pull the changes first
Check here https://vansh-codes.github.io/ChaosWeb/

**Comment by vansh-codes** [comment]
Ohh sorry my bad bro, you are asking to modify Testing page 
sor sorry
We dont require the testing page, can you integrate the functionality of testing page in all the pages??

**Comment by vansh-codes** [comment]
Do you still want to work on this or shall I close this issue?

**Comment by vansh-codes** [comment]
Sure go ahead!

**Comment by Mr-DK07** [comment]
> Sure go ahead!

@vansh-codes  Assign this to me..

**Comment by Mr-DK07** [comment]
@vansh-codes ??

**Comment by vansh-codes** [comment]
Create PR

**Comment by Mr-DK07** [comment]
@vansh-codes okay
