### ISSUE TITLE
Chaotic Feat: Glassmorphism Effect

### ISSUE THREAD

**Issue by Riya7045** [vansh-codes/ChaosWeb#170]
To enhance the design of the form, I want to incorporate the Glassmorphism effect. This design trend creates a visually appealing frosted glass appearance, combining blurred, semi-transparent backgrounds with vibrant accents. The effect should give the form a sleek and modern look, as if the elements are floating above the background, while still maintaining readability and a minimalistic aesthetic. This will add depth and a futuristic feel to the UI, making the form stand out and feel more interactive.

### Add Screenshots or Sketches

![Screenshot 2024-10-23 223307](https://github.com/user-attachments/assets/a45ea47c-b380-4d5d-a680-97dcb6fad2d2)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!

**Comment by Riya7045** [comment]
i want to ask this changes i should do in contact.css file or in any other file.

**Comment by vansh-codes** [comment]
yaa works

**Comment by Riya7045** [comment]
okay ,so i am making this change in contact.css file
