### ISSUE TITLE
Chaotic Feat: Add Parallax Scrolling Effect

### ISSUE THREAD

**Issue by Riya7045** [vansh-codes/ChaosWeb#171]
Parallax Scrolling Effect - I want to incorporate a Parallax Scrolling Effect into the design to create a sense of depth and motion as the user scrolls through the timeline. This effect will allow background elements to move at a slower pace than the foreground content, giving the illusion of layers and adding a more dynamic, immersive experience. The goal is to enhance the chaotic yet visually engaging atmosphere of the timeline, making it feel more interactive and modern while maintaining smooth and fluid transitions between different sections.

![image](https://github.com/user-attachments/assets/fcaae8ba-df6b-40ea-ae9d-f5c61146ef0c)

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead! Make sure you do this changes in React folder i.e. `chaosweb-v@2` folder

**Comment by Riya7045** [comment]
ok i will start working on this issue.
