### ISSUE TITLE
Documentation Chaos:📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [vansh-codes/ChaosWeb#172]
### Describe the Documentation Update

Issue Description

adding Stargazers and Forkers section to readme.md

Suggested Change

we can add Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @vansh-codes !

### Add References or Examples

![2024-10-23 (7)](https://github.com/user-attachments/assets/a8e61bf3-47b8-4ee0-b3e1-cb100f3cb9f4)

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!
