### ISSUE TITLE
Implement multiple chaotic things to the website (read desc.)

### ISSUE THREAD

**Issue by shubhagarwal1** [vansh-codes/ChaosWeb#175]
- Color Inversion Toggler
- Random Sound Effects
- Glitchy Text Animations
- Falling UI Elements
- Floating Images
- Invisible Buttons
- Shape-Shifting Buttons
- Delayed Responses on Click
- Screen Shake Effect
- Random Background Changes
- Drifting Cursors
- Upside-Down Text
- Text that Escapes Cursor
- Color Pulse Background
- Time-Warp Animation
- Hover Expanding Elements
- Dynamic Font Resizing
- Sudden Page Zoom
- Broken Links
- Spinning Icons
**I will be implementing best 5 selected by you** 
Hey @vansh-codes please allow me to do this, and please assign it to me

**Comment by vansh-codes** [comment]
- fallling ui elements
- shape shifting elements
- screen shake effect
- sudden page zoom
- time warp animation
Go ahead with these 5 for now
All the best!

**Comment by vansh-codes** [comment]
Please use issue templates from next time
