### ISSUE TITLE
Documentation Chaos:

### ISSUE THREAD

**Issue by milansamuel609** [vansh-codes/ChaosWeb#177]
### Describe the Documentation Update

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead! 
Make all the changes in CONTRIBUTING.md file and not in README

**Comment by milansamuel609** [comment]
> Go ahead! Make all the changes in CONTRIBUTING.md file and not in README

Sure 👍
