### ISSUE TITLE
Interactive Card Rollout for a Mesmerizing User Experience

### ISSUE THREAD

**Issue by charmi2109** [vansh-codes/ChaosWeb#179]
### Describe your chaotic idea

I'm envisioning an interactive layout where a stack of cards begins with each card neatly layered behind the other. As you click on the cards, they should dynamically "spread out" in a random or chaotic fashion across the screen. 

this makes the website more cool and chaotic!😁
Please assign me this issue.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/493845ee-9383-4685-b536-bcb2a13333ee)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Umm sounds good! Go ahead
