### ISSUE TITLE
Adding a Chaotic Search bar:

### ISSUE THREAD

**Issue by sayanp607** [vansh-codes/ChaosWeb#18]
### Describe your chaotic idea

Adding a responsive search bar which will make more chaos when user will search something on it. Please assign this task to me, I will surely make it more chaotic and interesting.

### Add Screenshots or Sketches

![Screenshot 2024-10-07 193555](https://github.com/user-attachments/assets/469ac3d5-420f-47ce-9d93-64fdf6e9d9f0)
I will create a chaotic search bar here in the header section. It will responsive for all the pages across.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Sure go ahead! 
- start working on the js and functionality and later on after merging #2 you can integrate and develop the ui for the searchbar

Keep up the chaos!
happy coding 🚀

**Comment by sayanp607** [comment]
Thank You So much @vansh-codes

**Comment by vansh-codes** [comment]
Are you working on this or shall I close this issue??

**Comment by sayanp607** [comment]
Yes, I will give the code tonight surely

**Comment by vansh-codes** [comment]
Okay 👍

**Comment by vansh-codes** [comment]
Completed 👍
