### ISSUE TITLE
UPDATE:rectangular box around the Chaos Web image is visible, which may not be intended

### ISSUE THREAD

**Issue by charmi2109** [vansh-codes/ChaosWeb#180]
### Describe your chaotic idea

The ChaosWeb image currently has a visible rectangular boundary box that may not blend well with the background. This creates an unintended visual separation between the circular logo and the rest of the design, causing the logo to appear "boxed in" rather than seamlessly integrated into the layout, which may slightly distract the users.

Please assign me this issue and help me make the website more aesthetic @vansh-codes !!

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/79d0f703-f5e5-491a-9eb5-5359d9ec71d7)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead
