### ISSUE TITLE
Documentation Chaos: Update README

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [vansh-codes/ChaosWeb#183]
### Describe the Documentation Update

The README file is currently very long, making it difficult to quickly reach specific sections. Adding a table of contents would improve navigation.

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

@vansh-codes please assign me this issue

**Comment by vansh-codes** [comment]
Its not required friend
Please search for another issue which I would be happy to assign it to you
I am closing this issue now
