### ISSUE TITLE
Lights Out game

### ISSUE THREAD

**Issue by samriddhitiwary** [vansh-codes/ChaosWeb#186]
### Describe your chaotic idea

Dive into the challenging world of LightsOut, where strategy meets puzzle-solving! Your objective is to turn off all the lights on the grid by clicking on them. Each click toggles the selected light and its adjacent neighbors. Can you find the winning strategy to extinguish all the lights? Perfect for players of all ages, this engaging game sharpens your critical thinking and problem-solving skills while providing hours of fun. Are you ready to conquer the grid?

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/7337d70d-7c2d-404f-ab2b-9eab9d5f86b3)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by samriddhitiwary** [comment]
@vansh-codes 

1. Unlike the original "Lights Out" game, where toggling one cell changes its neighboring cells, you could make it so toggling one cell causes random cells (not just neighbors) to toggle.

2. You can define a certain probability that any given cell in the grid will be affected, creating an unpredictable effect.

3.Randomly shuffle the grid layout, either every few seconds or upon each toggle. This creates an extra layer of unpredictability.
4.Alternatively, change the entire grid size on certain toggles, switching between, say, a 5x5, 7x7, and 9x9 grid.

**Comment by vansh-codes** [comment]
ok go ahead

**Comment by samriddhitiwary** [comment]
@vansh-codes Thank you I will start working on it
