### ISSUE TITLE
Chaotic Feat: Automation of project structure updation using GitHub workflows and Python scripts

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [vansh-codes/ChaosWeb#193]
### Describe your chaotic idea

Currently, the project doesn't have a project structure. And, it would be a bit difficult for newcomers to understand the project and how to add more chaos to it's existing structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier and enhance organised chaos(metaphor!).

I want to add a detailed project structure in a separate file(redirect in README.md) for the contributors to refer to and automate its updation process as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand the structure and spread more chaos to the project. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and a Python script will make the project more accessible to the Contributors and spread more chaos.

### Add Screenshots or Sketches

Sample of how the workflow would be automated and the project structure after updation in readme:
![image](https://github.com/user-attachments/assets/81e8ca29-70d3-421e-aabc-1a2e428f13d5)

![image](https://github.com/user-attachments/assets/0bc44243-5a2a-4e6e-8afc-e0dd9097515f)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
The project structure is already there in CONTRIBUTING.md file

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes the project structure is just showing the folders and not the content files in it. For example:
![image](https://github.com/user-attachments/assets/03f656de-2157-4231-97b0-a0398d25f430)

The files inside the assets tab is not shown here.
![image](https://github.com/user-attachments/assets/b3a96c2d-be2f-4498-9996-05d1253e2536)

**Comment by vansh-codes** [comment]
Ohh yes, so it will be automated you are saying?

**Comment by rajdeepchakraborty-rc** [comment]
Since the Structure would become much longer, I was thinking of not keeping the dependencies(.gitignore,etc). Rather keep the main file structure in a much detailed manner.

**Comment by rajdeepchakraborty-rc** [comment]
> Ohh yes, so it will be automated you are saying?

Yes I will write code to automate the process. I was trying out in one of my repositories. That is the sample that I have shared with you. Since I have not tried this out with any other repositories so I cannot share and other repositories samples with you

**Comment by vansh-codes** [comment]
yeah right, I am asking how will it be automated?
For ex:
If I create a new file, will it be automatically updated in the structure as well?

**Comment by rajdeepchakraborty-rc** [comment]
> yeah right, I am asking how will it be automated? For ex: If I create a new file, will it be automatically updated in the structure as well?

Yes, it will add automatically using GitHub workflows and Python scripts that will help the GitHub bot to update the structure automatically. I would prefer to make a separate file and update the structure there to avoid any clash with the main contributing file.

**Comment by vansh-codes** [comment]
go ahead!

**Comment by vansh-codes** [comment]
How much time will it take to create a PR?

**Comment by rajdeepchakraborty-rc** [comment]
Are you familiar with Github workflows? What I will be doing is similar to that but I will add another layer to it by writing python code to automate the process

**Comment by rajdeepchakraborty-rc** [comment]
> How much time will it take to create a PR?

It is late night for me write now and I have college tomorrow. It would be great if you provide me time till tomorrow. Since I have to test the feature too. I will share the updates of the work with you tomorrow after I have successfully implemented the feature. Since this is the first time I am trying it on someone's repository I want to work on it very carefully and try to make the best out of it.

**Comment by vansh-codes** [comment]
Sure have your time no worries!

**Comment by rajdeepchakraborty-rc** [comment]
I might need some time, but I ensure you that I will give my best into the work and hopefuly you will like it.

**Comment by vansh-codes** [comment]
Take your time brother no worries!

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes It is working finally after a lot of checks. There was a small issue but it caused a lot of problems in the feature. It is finally resolved.

**Comment by rajdeepchakraborty-rc** [comment]
I want your opinion on something. Since the Project structure is quite lengthy, I have made a separate file named **PROJECT_STRUCTURE.md** and have added a redirect to it. Where do you want me to add the following redirect within the README.md file:
![image](https://github.com/user-attachments/assets/eb2c5c31-a504-40ca-924b-f0f0511bf86d)

**Comment by rajdeepchakraborty-rc** [comment]
Also, this is how the file is looking:
![image](https://github.com/user-attachments/assets/09d581b9-1503-4dc9-a7be-10b070311be6)

**Comment by rajdeepchakraborty-rc** [comment]
Please let me know your thoughts on the changes. I hope you like it.

**Comment by vansh-codes** [comment]
Yeah its perfect, great work @rajdeepchakraborty-rc

**Comment by vansh-codes** [comment]
You can create PR for this so I can review your code as well

**Comment by rajdeepchakraborty-rc** [comment]
> @vansh-codes I want your opinion on something. Since the Project structure is quite lengthy, I have made a separate file named **PROJECT_STRUCTURE.md** and have added a redirect to it. Where do you want me to add the following redirect within the README.md file or any other file: ![image](https://private-user-images.githubusercontent.com/68934988/381649205-eb2c5c31-a504-40ca-924b-f0f0511bf86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDkyMDcsIm5iZiI6MTczMDMwODkwNywicGF0aCI6Ii82ODkzNDk4OC8zODE2NDkyMDUtZWIyYzVjMzEtYTUwNC00MGNhLTkyNGItZjBmMDUxMWJmODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE3MjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NGJmZTg4MDQ5MDM0ZmYzOWQ3YjkyODVhZmZkYWU1N2U4Y2VhNDdkMTc2YTIxNWE5YWYxOWVmOTJlM2ZjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.foZa1N_hdQNNLzNwNpnbWXfPDkVQ3xQbqFC8SwhEWZk)
> 
> Please let me know where you want this redirect to be in.

@vansh-codes please share your opinion on this

**Comment by rajdeepchakraborty-rc** [comment]
> Yeah its perfect, great work @rajdeepchakraborty-rc

Thanks for the words of appreciation. I am glad you liked it.

**Comment by vansh-codes** [comment]
Yeah its perfect the way you did!

**Comment by vansh-codes** [comment]
Good job! Keep it up!
Create a PR i will review, you can do this task for my second project also

**Comment by rajdeepchakraborty-rc** [comment]
> Yeah its perfect the way you did!

I asked about where you want me to keep the redirect message, in readme file or contributing.md file?

**Comment by rajdeepchakraborty-rc** [comment]
> Good job! Keep it up! Create a PR i will review, you can do this task for my second project also

Sure. Could you please share the other project that you are talking about?

**Comment by vansh-codes** [comment]
yup first lets get this one completed, create PR so I can review it better, I will share second proj link to you in the PR

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes I have opened the PR
