### ISSUE TITLE
 I need (Scroll for the Chaos) text to be written chaotically aswell. with all sorts of animations.

### ISSUE THREAD

**Issue by anshdeep0504** [vansh-codes/ChaosWeb#195]
### Describe your chaotic idea

 I need (Scroll for the Chaos) text to be written chaotically aswell. with all sorts of animations.

### Add Screenshots or Sketches

![Screenshot from 2024-10-30 05-43-19](https://github.com/user-attachments/assets/88a4948b-148e-45a3-9a12-de476c5f6bd6)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
go ahead!

**Comment by vansh-codes** [comment]
Work on the react folder
`chaosweb-v@2`

**Comment by vansh-codes** [comment]
Combine #196 in this
