### ISSUE TITLE
I need (Welcome to ChaosWeb) text to be written chaotically with all sorts of animation.

### ISSUE THREAD

**Issue by anshdeep0504** [vansh-codes/ChaosWeb#196]
### Describe your chaotic idea

I need (Welcome to ChaosWeb) text to be written chaotically with all sorts of animation.

### Add Screenshots or Sketches

![Screenshot from 2024-10-30 05-45-31](https://github.com/user-attachments/assets/c6c92ca0-4224-4a5c-a17b-205f1bc10997)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Combine it with #195 and create one PR for both, both are similar task and needs to be handled in one issue
