### ISSUE TITLE
Chaotic Feat: Navbar, Chaotic Time Line and Contact us Feature

### ISSUE THREAD

**Issue by Tamanna225** [vansh-codes/ChaosWeb#2]
**Navbar**: I want to create a Vertical Navbar Mentioning Each Sections of the website but as the name of the project Suggests it is chaos So it will lead to different Sections not the same as named.
**Chaotic TimeLine**: A timeline that will contain all the chaotic events in History according to time but again the twist is it will be randomly arranged not timeline would match with no event
**Contact Us Form**: An interactive Contact Us form which will ask user to add name, Phone number and Description and all but this will not be it when the user will submit the form it will display message "Ha Ha Not that Simply You are on Chaos So you will need to Contact us With Chaos" and ask user to add different things in different field like Name in place of Email Id and Phone number in Name.

### Add Screenshots or Sketches

N/A

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 🚀

**Comment by vansh-codes** [comment]
Share a rough drawing or design of what you have thought

**Comment by Tamanna225** [comment]
-All the elements will have different Sizes
-There will be different Shapes or Emojis in between to show chaos
-at the corner there will be multiple triangles of different size signifying chaos
-Each element of navbar will have different theme


![WhatsApp Image 2024-10-07 at 13 41 58_58062778](https://github.com/user-attachments/assets/510b3a40-fef4-459d-910c-7a2a3d1c58ed)

**Comment by KhawajaFashi** [comment]
You can also make the text of the contact form transparent so even if the user writes he will not be able to see the text and on the side, a message will be displayed that why aren't you writing

**Comment by vansh-codes** [comment]
Hey @KhawajaFashi, great idea but instead of making it transparent we can use a animation just how it is for skeletons
I would like you to work on this after she completes basic setup!
If you are interested, then create a new issue for the same titled
`Add animations to input text in Contact page`
keep up the chaos!

**Comment by KhawajaFashi** [comment]
> Hey @KhawajaFashi, great idea but instead of making it transparent we can use a animation just how it is for skeletons
> I would like you to work on this after she completes basic setup!
> If you are interested, then create a new issue for the same titled
> `Add animations to input text in Contact page`
> keep up the chaos!

Yes I would gladly work on it. although I have never done that before but I would love to try it.
