### ISSUE TITLE
Chaotic Feat: Sign In with validation

### ISSUE THREAD

**Issue by isimarjitsingh** [vansh-codes/ChaosWeb#20]
### Describe your chaotic idea

as i observe  your website need a  sign in page please give that opportunity to me i am also sharing my screenshot of login form if you like it then please assign me to contribute in your project : ) .GSSOC extd

### Add Screenshots or Sketches

![Screenshot 2024-10-07 204407](https://github.com/user-attachments/assets/228bee29-1306-4b3f-8eda-cd17eb766be2)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
The issue already exists
#5
