### ISSUE TITLE
Chaotic Feat: I feel the background  which is  plane white could be edited to change colors too.

### ISSUE THREAD

**Issue by anshdeep0504** [vansh-codes/ChaosWeb#202]
### Describe your chaotic idea

Chaotic Feat: I feel the background  which is  plane white could be edited to change colors too.

### Add Screenshots or Sketches

![Screenshot from 2024-10-30 21-59-17](https://github.com/user-attachments/assets/4a643feb-288b-4112-b8a2-8a2ab319bc01)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
go ahead!
