### ISSUE TITLE
Chaotic Feat: I feel i can add some crazy dancing emojis on the same page to make it  chaotic.

### ISSUE THREAD

**Issue by anshdeep0504** [vansh-codes/ChaosWeb#205]
### Describe your chaotic idea

Chaotic Feat: I feel i can add some crazy dancing emoji on the same page around the text to make it more chaotic.

### Add Screenshots or Sketches

![Screenshot from 2024-10-30 23-39-22](https://github.co@vansh-codes er-attachments/assets/dfa6387b-6aea-4e8e-84c6-cf022df69ab1)
@vansh-codes help me work on this.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
go ahead, but you should've done it in the same issue and PR
