### ISSUE TITLE
Chaotic Feat:Adding random popups

### ISSUE THREAD

**Issue by Jordian0** [vansh-codes/ChaosWeb#208]
### Describe your chaotic idea

Adding random popups on the screen with funny messages.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/839ca215-5005-4f34-aa48-5ea5c185a3d2)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .

**Comment by Jordian0** [comment]
Bro! I've already asked them to assign me!!
