### ISSUE TITLE
Chaotic Feat:Random background color change every second

### ISSUE THREAD

**Issue by Jnanvesha04** [vansh-codes/ChaosWeb#21]
### Describe your chaotic idea
@vansh-codes 

 Random Background Color Change Every Second
Description: The background color of the page should change every second, choosing random RGB values. This feature enhances the chaotic look and feel of the page, with unpredictable color shifts.

Expected Behavior:

Background color changes every second.
The RGB values should be randomly generated for each change.
The transition is immediate with no smooth effect, emphasizing randomness.

### Add Screenshots or Sketches

Background color changes every second.
The RGB values should be randomly generated for each change.
The transition is immediate with no smooth effect, emphasizing randomness.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Keeping this issue on hold for a while
I will update you on this later!

**Comment by Jnanvesha04** [comment]
Okayy

**Comment by vansh-codes** [comment]
You can implement this now! make sure to make it reusable
Happy Contributing
Feel free to contact here or raise a discussion [here](https://github.com/vansh-codes/ChaosWeb/discussions) anytime!

**Comment by Jnanvesha04** [comment]
@vansh-codes done changes  its totally reusable 
Add codes in script.js file 
![IMG_20241008_141254](https://github.com/user-attachments/assets/9441e463-543a-4f98-9097-7a848a9a810f)
![IMG_20241008_141309](https://github.com/user-attachments/assets/4487beef-a41c-44f3-a687-3cf822e759db)
![Screenshot_2024-10-08-14-15-31-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/ff1f42af-c3fb-4615-a602-eccc42e9427c)

Create a pull request please accept it

**Comment by vansh-codes** [comment]
No need to add screenshots of codde and Pull request created, you should add screenshots and videos of the work done

**Comment by vansh-codes** [comment]
Done 👍
