### ISSUE TITLE
Chaotic Feat: Create a Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by myselfshivams** [vansh-codes/ChaosWeb#213]
### Describe your chaotic idea

Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

### Add Screenshots or Sketches

I will add custom 404 page according to current style.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead
