### ISSUE TITLE
Chaotic Feat:Chaotic animation with erratic box movement 

### ISSUE THREAD

**Issue by Jnanvesha04** [vansh-codes/ChaosWeb#22]
### Describe your chaotic idea

@vansh-codes 
 Chaotic Animation with Erratic Box Movement
Description: The boxes on the page should move unpredictably across the screen, with random translations, rotations, and speed changes. The movement should create a chaotic visual effect.

Expected Behavior:

Boxes move randomly across different parts of the screen.
Boxes rotate randomly at different angles during movement.
The animation loops infinitely with random patterns.

### Add Screenshots or Sketches

Boxes move randomly across different parts of the screen.
Boxes rotate randomly at different angles during movement.
The animation loops infinitely with random patterns.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Can you share some pictures/sketches/designs ?
Will you be using any external libraries for this or you gonna create on your own?

**Comment by Jnanvesha04** [comment]
https://github.com/user-attachments/assets/3147e982-3aa6-44eb-8ea9-87fadc2927ae

Here is a small clip

**Comment by vansh-codes** [comment]
Where we will add this?

**Comment by Jnanvesha04** [comment]
![Screenshot_2024-10-08-00-21-27-79_f9a7afa717ced9e1fc9be9833291031a](https://github.com/user-attachments/assets/42d3f082-7d9e-4ec2-b895-ee2ef7ebb592)

Here!!

**Comment by vansh-codes** [comment]
I am keeping this on pending, will let you know once the main page and basic structure is ready
I will notify you

**Comment by vansh-codes** [comment]
Do you still want to work on this? 
If yes then you can let me know and start working and complete it asap
