### ISSUE TITLE
Documentation Chaos:The hactober fest image is not correct in the readme.md

### ISSUE THREAD

**Issue by likitha-kapu** [vansh-codes/ChaosWeb#220]
### Describe the Documentation Update

I think the hactober fest image in the readme file is incorrect.The image should be this 
![image](https://github.com/user-attachments/assets/a7a187b6-b69c-4276-b68b-313262714c94)

### Add References or Examples

![image](https://github.com/user-attachments/assets/a9312d39-cab0-4bca-aa30-1a81024e1cab)

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor

**Comment by vansh-codes** [comment]
Hey @likitha-kapu , thanks for noticing and raising issue, but be aware I cant give any points for this issue, if you are still interesting then go ahead otherwise feel free to close the issue

**Comment by likitha-kapu** [comment]
@vansh-codes yeah that's fine...can you add me hacktoberfest label

**Comment by vansh-codes** [comment]
Hacktoberfest has ended so it wont do anything now

**Comment by likitha-kapu** [comment]
@vansh-codes yeah fine..thank you
