### ISSUE TITLE
Documentation Chaos: sliding cards animation for contributors

### ISSUE THREAD

**Issue by KGupta2601** [vansh-codes/ChaosWeb#222]
### Describe the Documentation Update

I want to add the sliding cards animations for displaying the name and profile of the contributors along with the number of contributions

### Add References or Examples

![image](https://github.com/user-attachments/assets/618088b5-af9f-49ba-94c7-457c3f790c04)
![WhatsApp Image 2024-11-05 at 17 57 44_f6636291](https://github.com/user-attachments/assets/4a88f1d5-e3f4-4fc1-915d-5ea1c94945e4)
the cards will keep on sliding

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor

**Comment by KGupta2601** [comment]
@vansh-codes kindly assign me this issue along with the level label

**Comment by vansh-codes** [comment]
go ahead

**Comment by vansh-codes** [comment]
Do it in React folder `chaosweb-v@2`

**Comment by KGupta2601** [comment]
> Do it in React folder `chaosweb-v@2`

yup sure

**Comment by vansh-codes** [comment]
Completed
