### ISSUE TITLE
Chaotic Feat:Chaotic Neon Easter Eggs

### ISSUE THREAD

**Issue by samriddhitiwary** [vansh-codes/ChaosWeb#224]
### Describe your chaotic idea

Uncover hidden surprises in this neon-themed interactive web page, where chaos and color collide! Engage with a variety of exciting features designed to keep you entertained. Hover over the secret area to reveal a hidden button and unlock a fun reward, accompanied by a sound effect. Click the interactive shapes to change their style and color dynamically, while a rotating set of 100 random shapes appears around the screen for an extra dose of chaos.

Experience an explosive confetti shower with a button click, filling the screen with colorful particles. Additionally, a collection of 200 unique emojis will fall from the top of the screen, bouncing on impact and disappearing in a fun, bouncy animation. Neon lights and 3D effects make this playful journey even more exciting. This interactive page is a playful homage to hidden Easter eggs, perfect for those who love surprises and vibrant designs!

### Add Screenshots or Sketches

Experience an explosive confetti shower with a button click, filling the screen with colorful particles. Additionally, a collection of 200 unique emojis will fall from the top of the screen, bouncing on impact and disappearing in a fun, bouncy animation. Neon lights and 3D effects make this playful journey even more exciting. This interactive page is a playful homage to hidden Easter eggs, perfect for those who love surprises and vibrant designs!

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor

**Comment by samriddhitiwary** [comment]
@vansh-codes Could you please assign this to me

**Comment by vansh-codes** [comment]
go ahead

**Comment by vansh-codes** [comment]
Completed
