### ISSUE TITLE
Chaotic Feat:Chaotic Typing Universe

### ISSUE THREAD

**Issue by samriddhitiwary** [vansh-codes/ChaosWeb#226]
### Describe your chaotic idea

Welcome to the "Chaotic Typing Universe," where your every click and keypress ignites a burst of random letters and emojis that scatter across the screen in a mesmerizing and unpredictable dance. As you type, the text scrambles itself, adding an extra layer of chaos to your typing experience. With every click, 100 random characters or emojis appear near your cursor, spinning and fading away as if pulled by some cosmic force. This immersive experience is filled with colorful visual effects, including random chaotic elements, thunderbolt animations, and flickering backgrounds, designed to make typing feel like an out-of-control adventure in a digital universe.

### Add Screenshots or Sketches

Welcome to the "Chaotic Typing Universe," where your every click and keypress ignites a burst of random letters and emojis that scatter across the screen in a mesmerizing and unpredictable dance. As you type, the text scrambles itself, adding an extra layer of chaos to your typing experience. With every click, 100 random characters or emojis appear near your cursor, spinning and fading away as if pulled by some cosmic force. This immersive experience is filled with colorful visual effects, including random chaotic elements, thunderbolt animations, and flickering backgrounds, designed to make typing feel like an out-of-control adventure in a digital universe.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor

**Comment by samriddhitiwary** [comment]
@vansh-codes Could you please assign this issue to me

**Comment by vansh-codes** [comment]
Will you do this task in React??

**Comment by samriddhitiwary** [comment]
@vansh-codes Actually I have already made in html
Is that okay?

**Comment by vansh-codes** [comment]
Can you do it in React, it would be better as we have to remove html website

**Comment by samriddhitiwary** [comment]
@vansh-codes 
I can do it in React, is there any other ReactJs Repo for this project?

**Comment by vansh-codes** [comment]
No in this only there is `chaoswebv@2` folder for react

**Comment by samriddhitiwary** [comment]
@vansh-codes Ok
