### ISSUE TITLE
Chaotic Feat:Broken button with unpredictable results

### ISSUE THREAD

**Issue by Jnanvesha04** [vansh-codes/ChaosWeb#23]
### Describe your chaotic idea

 @vansh-codes assign me this 
Broken Button with Unpredictable Results
Description: The button should not perform any useful function, mimicking chaotic behavior. Clicking the button should either trigger a random alert message or simply change the text displayed on the button, without achieving any productive result.

Expected Behavior:

On click, the button sometimes changes its text to "Nothing happened!" or a similar message.
Alternatively, clicking the button triggers a random alert message like "You clicked the button but nothing works!".
The button’s behavior should be inconsistent to emphasize chaos

### Add Screenshots or Sketches

On click, the button sometimes changes its text to "Nothing happened!" or a similar message.
Alternatively, clicking the button triggers a random alert message like "You clicked the button but nothing works!".
The button’s behavior should be inconsistent to emphasize chaos

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Seems good!
Dont use browsers alert function, create a custom chaotic alert
Wait for #2 to be complete, then you can start working
I am assigning it to you!
Keep up the chaos!
happy contributing 🚀

**Comment by Jnanvesha04** [comment]
@vansh-codes 
Okay!!
And thank you for assigning this to me !

**Comment by Jnanvesha04** [comment]
@vansh-codes done!!
Accept my pull request!
![Screenshot_2024-10-08-14-51-08-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9c3fc9b5-d11c-4839-a373-469bf9d0f837)
![Screenshot_2024-10-08-14-54-08-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4bd4292c-b757-40b5-abe9-593ce7017ce0)
