### ISSUE TITLE
Chaotic Feat: Add a hypnotic section on the website

### ISSUE THREAD

**Issue by anshika-1102** [vansh-codes/ChaosWeb#24]
### Describe your chaotic idea

Introduce a feeling of a glitching mind with swirling patterns and shifting colors to disorient and captivate users. 
This feature would create an unpredictable, hypnotic effect that amplifies the chaotic theme of the site.

### Add Screenshots or Sketches

I haven't worked on this issue. So I do not have any screenshot for the same.

![image](https://github.com/user-attachments/assets/58f732ea-5148-4672-bb54-7995b25eb1df)

But it can be made in a way that the above patterns rotate on a very high speed with very disturbing background colors.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Wow seems chaotic 💥 
great idea 💡 
You can start working on the page and later integrate it with the main page when #2 is completed
Keep up the chaos!

**Comment by anshika-1102** [comment]
Thank you @vansh-codes . I'll update when I'm done with the work.

**Comment by anshika-1102** [comment]
hey @vansh-codes please review the webpage.

https://github.com/user-attachments/assets/5562e613-2a2f-4d6f-a06d-593fe5ba95f1

In case you are satisfied with it, I'll add a PR for the same.

**Comment by vansh-codes** [comment]
Sure go ahead and create a PR

**Comment by vansh-codes** [comment]
Completed 👍
