### ISSUE TITLE
Chaotic Feat:

### ISSUE THREAD

**Issue by Aryan-01-star** [vansh-codes/ChaosWeb#26]
### Describe your chaotic idea

Hey, chaos I think we can edit this website in terms of both UI/UX and features so let's work on it,also this website can have much more to add in itself .

 

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/31d3f7c6-1e5b-47b1-b105-2e58c413ff56)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Its been done by #2 
Lets wait till its done then you can let me know if you have any further idea!
Till that time lets keep this on hold!

**Comment by vansh-codes** [comment]
You can check the current UI and porpose changes to me so we can decide and move further

**Comment by Aryan-01-star** [comment]
isn't the one whose screenshot I have attached above the current website UI, if so then can you provide me with the link to that
that will be of great help

**Comment by Aryan-01-star** [comment]
We can update this page as all the content are not visible until we reduce the screen size 
the preview without any minimized screen
![image](https://github.com/user-attachments/assets/ee6ed7bc-bd24-4356-9056-0c8a7601b3cf)
the preview with reduced screen size 
![image](https://github.com/user-attachments/assets/6e2c19a4-0b8c-4198-9f4d-d2c4d755b011)

**Comment by vansh-codes** [comment]
You can descrease the sign of the images and boxes or constraint the area for the images

**Comment by vansh-codes** [comment]
Are you still interested in doing this task?
If yes then let me know and start working on it asap

**Comment by Aryan-01-star** [comment]
I have solved the issues and also created a pull request to it

**Comment by Aryan-01-star** [comment]
Hey @vansh-codes please have a check and refer me if your thoughts

**Comment by vansh-codes** [comment]
@Aryan-01-star what are you talking about?

**Comment by Aryan-01-star** [comment]
my bad it was a typo mistake I was saying that I have solved the issue please drop a review for that

**Comment by vansh-codes** [comment]
Where bro? can you explain what you mean, I still didnt get your point
