### ISSUE TITLE
Chaotic Feat: Chaotic Cursor Overload When Clicking a Button

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [vansh-codes/ChaosWeb#28]
### Describe your chaotic idea

**Problem:**
Users will encounter chaotic and frustrating behavior when they try to interact with the website's buttons. Upon attempting to click any button, multiple mouse cursors suddenly appear on the screen, creating confusion and making it nearly impossible to interact with the intended element.

**Reproduction Steps:**
1. Navigate to any  interactive buttons.
2. Attempt to hover over or click a button.
3. Observe multiple cursors appearing across the screen, obstructing the user’s ability to click the desired button.

**Expected Behavior:**
When a user hovers or clicks a button, only one cursor should remain visible, and the interaction should be smooth and predictable.

**Actual Behavior:**
Upon clicking a button, multiple cursors appear and scatter across the screen, confusing the user and disrupting the intended action.

---
@vansh-codes kindly add proper labels 

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/27e5df5a-12b1-40f1-a520-f99c7917a151)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Chaotic idea!
Propposed Modifications:
- instead of static cursor spawn, make it dynamic, all the cursors should move so user will be confused more about his cursor
- make sure to handle the number of cursors appearing to prevent hanging user's device/website

**Comment by vansh-codes** [comment]
Do you wanna work on this or shall I close this issue?

**Comment by idk-mr4tyunjay** [comment]
> Do you wanna work on this or shall I close this issue?

Sorry, I am currently engaged with something so I won't be able to work on it
