### ISSUE TITLE
Documentation Chaos: Add auto-comment bot on new issue

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/ChaosWeb#3]
### Describe the Documentation Update

- I want a auto-comment bot on this repo which will comment when a new issue is created
Message should be:
`👋 Thanks for opening this issue! We appreciate your contribution. Please make sure you’ve provided all the necessary details and screenshots, and don't forget to follow our Guidelines and Code of Conduct. Happy coding! 🚀`

- A bot comment when issue is closed
Message should be:
`✅ This issue has been successfully closed. Thank you for your contribution and helping us improve the project! If you have any more ideas or run into other issues, feel free to open a new one. Happy coding! 🚀`

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by LitZeus** [comment]
hey @vansh-codes  Can I look into the issue?

**Comment by vansh-codes** [comment]
@LitZeus Sorry buddy! Its first come first serve! You can find and create new issues
