### ISSUE TITLE
CHAOS REPORT:No Follow us section at bottom

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [vansh-codes/ChaosWeb#31]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

No Follow us section at bottom

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
have solved this issue added the follow us section at bottom using the contact links
<img width="847" alt="b" src="https://github.com/user-attachments/assets/189da368-45a3-4861-8e6f-f01a30c07c0f">

**Comment by vansh-codes** [comment]
No need for this!
Create some other issues which I will be happy to assign!
