### ISSUE TITLE
add a random color generation on boxes

### ISSUE THREAD

**Issue by bhavanireddy57** [vansh-codes/ChaosWeb#32]
### Describe your chaotic idea

I want to add a feature of adding random color to boxes when they are moving so that it looks even more chaotic

### Add Screenshots or Sketches

https://github.com/user-attachments/assets/e592f480-6002-46af-bef3-40d2a9ca3966

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by bhavanireddy57** [comment]
I want to work on this can you please assign me this task.

**Comment by bhavanireddy57** [comment]
As shown in above video I have added random color generation to boxes when they are moving So please assign this to me

**Comment by bhavanireddy57** [comment]
I have looked into it I can contribute to you immediately can u assign me this.

**Comment by vansh-codes** [comment]
Great idea, just descrease the time of color changing on a box, its changing too rapidly giving constraint on eyes which is not good!
