### ISSUE TITLE
Sign In Page:

### ISSUE THREAD

**Issue by sayanp607** [vansh-codes/ChaosWeb#33]
### Describe your chaotic idea

The Sign In page present in the index.html route or home page redirects or navigates to the home page again on clicking on it. It should navigate to a different route/page where the user can sign in. Please assign this task to me, I will do it completely and whiling signing in the user should feel a chaotic environment.

### Add Screenshots or Sketches

![Uploading IMG_20241008_094551.jpg…]()
I will add chaotic sound effect in this form. While user fill the form or while submit it by clicking the sign in button, chaos will be generated

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
This issue already exists #5 
Please bring up new ideas and issues which dont exist already
