### ISSUE TITLE
Chaotic Feat: Fix width of timeline page and fix animation.

### ISSUE THREAD

**Issue by Mr-DK07** [vansh-codes/ChaosWeb#34]
### Describe your chaotic idea

Hey @vansh-codes  I wanted to fix the animation of timeline page. It's width is going outside of the page. It is not a good way to show timeline.
It should be fixed so that it can make a good user experience.

### Add Screenshots or Sketches

![Screenshot 2024-10-08 101837](https://github.com/user-attachments/assets/bf98e38c-422b-4dc9-b580-0d4e1451b784)

Please assign me this, so I can fix it.
make sure to add labels (gssoc-ext, hactoberfest , level1, level2, level3).

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 🚀

**Comment by vansh-codes** [comment]
You wanna complete this or shall I close this issue?

**Comment by Mr-DK07** [comment]
> You wanna complete this or shall I close this issue?

It's already done.
