### ISSUE TITLE
Chaotic Feat: want to fix home page animation

### ISSUE THREAD

**Issue by Mr-DK07** [vansh-codes/ChaosWeb#35]
### Describe your chaotic idea

Hey @vansh-codes There is the animation on home page, by this all the navigation items moving unnecessary. It create a disturbance at the time of clicking any one of them. Also this is not much user friendly. 

So wanted to fix these in the form of a attractive navigation bar including animation.

### Add Screenshots or Sketches

![Screenshot 2024-10-08 103149](https://github.com/user-attachments/assets/a6ae1300-6eb5-4041-b2a9-10753db6dc65)

Could you assign me this, so that I can start working on this.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
I guess thats what chaos is!!
If you will fix it then there wont be any chaos 😉 
You can search for some other chaotic issues
