### ISSUE TITLE
add a jokes notification when trying to chase boxes

### ISSUE THREAD

**Issue by bhavanireddy57** [vansh-codes/ChaosWeb#38]
### Describe your chaotic idea

I would like to add a jokes notification when user trying to select a box

### Add Screenshots or Sketches

https://github.com/user-attachments/assets/cf740beb-d36d-4895-82eb-862dc210d01e

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by bhavanireddy57** [comment]
Can you assign me this I want to work on this

**Comment by vansh-codes** [comment]
Boxes are the navbar buttons, they redirect to different pages, can you ellaborate your idea or make some changes to fit it into the current page

**Comment by bhavanireddy57** [comment]
The jokes notification appears when only moving my cursor towards boxes but when i click on boxes jokes  doesnot appear and then redirect to page functionality.

**Comment by vansh-codes** [comment]
Can we make it appear as a popup everytime user goes to a different page?
ex:
I click on contact us button and reach to contact page and then we get a joke popup for 5-10 second

Can you do it this way?

**Comment by bhavanireddy57** [comment]
OK I will work on it.

**Comment by vansh-codes** [comment]
Any updates @bhavanireddy57 ??
