### ISSUE TITLE
Chaotic Feat: Creation of ChaosWeb logo

### ISSUE THREAD

**Issue by kanduru-abhiram** [vansh-codes/ChaosWeb#4]
### Describe your chaotic idea

I just read the idea documentation of ChaosWeb and it's like totally unpredictable. I would love designing the logo for the website as per the documentation mentioned.

Kindly assign me this issue under Hacktoberfest2024 and please do add hacktoberfest,hacktoberfest-accepted and hactoberfest2024 labels for easy assignation. 

### Add Screenshots or Sketches

Not yet started but will defintely do something useful. I'm not that good at animation but will design logo from simple editors. Do check out my youtube channel where I do youtube series with new logo designs.

abhiram.bio.link

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 🚀
Note: 
- create a assets folder and keep the logo in that folder
- create .svg, .png and .ico formats of the logo as well
- logo should be in high quality

**Comment by Ek-ta-bharti** [comment]
I would like to work on this. Please assign this to me.

**Comment by vansh-codes** [comment]
Its already assigned to @kanduru-abhiram 
Please search for new issues @Ek-ta-bharti instead of commenting on other issues which are already assigned
