### ISSUE TITLE
CHAOS REPORT:Addind Contact us page 

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [vansh-codes/ChaosWeb#44]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

i will make a new page openend when contact us is clicked up and it will make the website more responsive!!
please assign me with the required labels as per gssoc'24 extended program

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
ContactUs page already exists

**Comment by vansh-codes** [comment]
vansh-codes.github.io/ContactUs.html

**Comment by vansh-codes** [comment]
The url for the same is mentioned wrong, you can fix it and refactor the contact form as well
Can you do this task??

**Comment by BVPKARTHIKEYA** [comment]
![image](https://github.com/user-attachments/assets/dbdd3d7d-4045-4b81-a826-b4b1f79a932d)
 but when i am clicking on the contact option it is not redirecting to that page!!
please assign me this issue with required labels!!

**Comment by vansh-codes** [comment]
Yes the address is done wrong by contributor
you can fix it
Here the file
https://github.com/vansh-codes/ChaosWeb/blob/main/ContactUs.html

**Comment by BVPKARTHIKEYA** [comment]
okay!!

**Comment by sameer-soni** [comment]
are you still working on this issue? If no, can i get assigned?

**Comment by vansh-codes** [comment]
Its done, @sameer-soni I will notify you once its migrated to React, can you work on React!?
If yes then I would like you to work after its ready in React!

**Comment by sameer-soni** [comment]
@vansh-codes yeah sure, let me know when you are done migrating.
