### ISSUE TITLE
Documentation Chaos: Can add countributors github profiles in read me file.

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [vansh-codes/ChaosWeb#46]
### Describe the Documentation Update

showcase all contributors github profiles that have contributed up till now.

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Create a new file `CONTRIBUTORS.md` and add it there
add a chaotic design

**Comment by vansh-codes** [comment]
Completed 👍
