### ISSUE TITLE
Chaotic Feat: Reverse Scrolling Maze

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [vansh-codes/ChaosWeb#47]
### Describe your chaotic idea

add reverse scrolling maze fun game element on homepage with other elements(signup, about us, contact, testing etc)
This is a mini-game where users navigate a maze, but the controls are completely reversed (e.g., up goes down, left goes right). The maze could appear randomly as users scroll through the page.

### Add Screenshots or Sketches

NA

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Can you share a design/sketch/screenshot/video so I can undnerstand it better??

**Comment by Rashigera** [comment]
Could you please assign this to me

**Comment by vansh-codes** [comment]
@SanikaBhalerao1345 are you interested in doing this or Shall i assign it to @Rashigera ??
You should respond within 24hours otherwise it will be assigned to @Rashigera

**Comment by SanikaBhalerao1345** [comment]
@vansh-codes yes I'm interested in doing it. I have already started working on it, will send snippets by evening today.

**Comment by Rashigera** [comment]
Hey @SanikaBhalerao1345  could you please include me to this project issue with you just for learning

**Comment by SanikaBhalerao1345** [comment]
@Rashigera i have already worked upon this issue, and I'm also a beginner contributor. srry, pls contact mentors or take some level 1 issues.

**Comment by SanikaBhalerao1345** [comment]
@vansh-codes this is how maze will look and how it will function:
how maze will look:
![image](https://github.com/user-attachments/assets/7ad9f658-6feb-4790-a5f5-c04b8e848176)

after pressing up arrow key blue box moves down
![image](https://github.com/user-attachments/assets/d222adc9-c75c-47e7-a879-811c59e23775)

after pressing left arrow key blue box moves right
![image](https://github.com/user-attachments/assets/401891e0-910a-4548-935d-643b73fc978a)

and likewise the arrowkeys perform reverse action on blue box
can you pls assign this issue to me with labels so i can create PR

**Comment by vansh-codes** [comment]
Create a PR if its completed, make sure it is responsive

**Comment by vansh-codes** [comment]
Completed 👍
