### ISSUE TITLE
Chaotic Feat: improving UI of the signup page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [vansh-codes/ChaosWeb#49]
### Describe your chaotic idea

the signup page can be improved .
@vansh-codes if you can assign me this ill fix it immediately.

### Add Screenshots or Sketches

<img width="956" alt="Screenshot 2024-10-08 at 8 46 14 PM" src="https://github.com/user-attachments/assets/76f51f73-4c03-4be7-8210-4c71aee7de8d">

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by JOSHITHA6** [comment]
Please assign this task to me @vansh-codes under the label gssoc'24 extd and hacktoberfest'24

**Comment by vansh-codes** [comment]
What improvement would you like to do, please share snapshots and describe in brief

**Comment by JOSHITHA6** [comment]
I would like to improve the contact us page.
