### ISSUE TITLE
Chaotic Feat:Sign up and Sign in page

### ISSUE THREAD

**Issue by Sakshamp19** [vansh-codes/ChaosWeb#5]
### Describe your chaotic idea

The signup page will redirect to signin page and vice versa.
default structure of the page will be horizontal

### Add Screenshots or Sketches

NA

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 🚀
Note:
- provide a default skethc/design for your task later

**Comment by vansh-codes** [comment]
You can start working!

**Comment by vansh-codes** [comment]
Are you working on it?

**Comment by vansh-codes** [comment]
@Sakshamp19 ??
