### ISSUE TITLE
Improve Hover Experience and Create an Interactive Review Section

### ISSUE THREAD

**Issue by devki412** [vansh-codes/ChaosWeb#54]
This issue focuses on enhancing user interactions with hover effects and creating a dynamic review section. The goal is to keep the chaotic theme while ensuring a delightful user experience. When users hover over buttons or review elements, unexpected but fun effects should occur, keeping the design playful yet functional. @vansh-codes PLZ ASSIGN THIS ISSUE.

**Comment by vansh-codes** [comment]
The website will be migrated to react
Check #53 
For the time being, I am keeping this issue on hold

**Comment by vansh-codes** [comment]
@devki412 do you wanna work on this or shall I close this issue?

**Comment by devki412** [comment]
I can do it after 3 days currently i have my exams so plz after 3 days i complete it within a day.

________________________________

**Comment by vansh-codes** [comment]
Okay get it done by maximum 25th October

**Comment by devki412** [comment]
Ohk ..
Thank you for your understanding

________________________________

**Comment by devki412** [comment]
but u dont assign me this issue @vansh-codes

**Comment by devki412** [comment]
thankyou I start working now.
