### ISSUE TITLE
Chaotic Feat: Colorful Background Animation

### ISSUE THREAD

**Issue by sv410** [vansh-codes/ChaosWeb#57]
### Describe your chaotic idea

Implement a background that constantly changes colors in an unpredictable pattern. The colors should switch randomly at different intervals to create a chaotic atmosphere.
Add a pulsing animation to further amplify the effect, making the background feel "alive."

### Add Screenshots or Sketches

This animation adds an illusion of depth to your background creating a parallax scrolling stars effect. It uses a simple SASS function (to create a random star field on each load) and CSS animation keyframes.

![css animation](https://github.com/user-attachments/assets/317bfeba-5954-4e51-84d7-8b2d63d8e31d)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Its a great idea but we are currently migrating the website from html,css,js to reactjs
Check #53 for more information

I would love if you can do the same task in react after migration is completed
Let me know your thoughts if you are open to do this in React or not??

**Comment by sv410** [comment]
i can with the sass, haml , js! in which i can covert that to react and also can do it

**Comment by vansh-codes** [comment]
Okay then, wait for the website to be converted to react then I will notify you so you can do it

**Comment by sv410** [comment]
pls add GSSOC, ` Hacktoberfest tag.`

**Comment by sv410** [comment]
can you pls add some level tag! thanks a lot and would love to work on it in future!

**Comment by vansh-codes** [comment]
https://github.com/vansh-codes/ChaosWeb/tree/main/chaosweb-v%402

If you are interested you can let me know and start working on it, heres the link to react folder

**Comment by sv410** [comment]
@vansh-codes Thank you for sharing the link! I’m definitely interested and will start working on it. I’ll keep you updated on my progress and let you know once it’s done.

**Comment by vansh-codes** [comment]
Sure!

**Comment by vansh-codes** [comment]
Any updates @sv410  ????

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me.

**Comment by vansh-codes** [comment]
Go ahead @manastiwari99 
Please work on the react folder, I have shared its link above in previous comments
