### ISSUE TITLE
Chaotic Feat: Dancing words

### ISSUE THREAD

**Issue by KAmaL-senpai** [vansh-codes/ChaosWeb#58]
### Describe your chaotic idea

I can add a new feature here user input dances.

### Add Screenshots or Sketches

https://github.com/user-attachments/assets/c924a073-1690-46ea-858c-986fbc5aaf15

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Would love to have this in React after the website is migrated
Can you do this in React??

**Comment by KAmaL-senpai** [comment]
yes i will be able to do it.

**Comment by vansh-codes** [comment]
Sure I will let you know once it is migrated to react so after it you can do this in React

**Comment by vansh-codes** [comment]
Go ahead @KAmaL-senpai

**Comment by vansh-codes** [comment]
Whats the update @KAmaL-senpai ??

**Comment by KAmaL-senpai** [comment]
@vansh-codes i have created a pull request check.
