### ISSUE TITLE
Chaotic Feat:  add contact us page

### ISSUE THREAD

**Issue by eshaalal** [vansh-codes/ChaosWeb#59]
### Describe your chaotic idea

1. I want to use GSAP 
2. Use scrollTrigger

### Add Screenshots or Sketches

contact page shows error
![Screenshot 2024-10-09 114709](https://github.com/user-attachments/assets/26478953-1855-4453-afc3-8750ab248434)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] #61
- [X] I'm Hacktoberfest registered Contributor

**Comment by eshaalal** [comment]
@vansh-codes please assign me this task under level-3

**Comment by vansh-codes** [comment]
Website is been migrated to Reat 
Check #53 

If you interested in implementing it in React then you can otherwise you may close the issue

**Comment by eshaalal** [comment]
@vansh-codes  Sure, I can work with react 👍

**Comment by vansh-codes** [comment]
Okay I will let you know when the migration is complete so you can start working on this!

**Comment by vansh-codes** [comment]
Go ahead!
use GSAP and work on REACT folder
`chaosweb-v@2`

**Comment by vansh-codes** [comment]
Are you still interested in working in this task or shall I close this issue?
