### ISSUE TITLE
Chaotic Feat: Footer

### ISSUE THREAD

**Issue by Prashant1659** [vansh-codes/ChaosWeb#6]
### Describe your chaotic idea

There will be customised footer at the end of page 
It will be aligned horizontally with the website 

### Add Screenshots or Sketches

NA

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 🚀
Note:
- provide a sketch/design for your task
- try to make it responsive for all screens

**Comment by vansh-codes** [comment]
You can start working!

**Comment by vansh-codes** [comment]
Are you working on this??

**Comment by coding-geek-nm** [comment]
@vansh-codes i would like to contribute to this issue . Can u assign me this issue?

**Comment by vansh-codes** [comment]
@coding-geek-nm Explain your idea to make the footer chaotic in brief

**Comment by coding-geek-nm** [comment]
Describe your chaotic idea:

1. A dynamic footer will be implemented at the bottom of the website, aligned horizontally with the overall layout.(and responsive too).
2. Footer will include links to essential contact information, such as email, social media profiles, and GitHub repositories, ensuring easy communication.
3. A dedicated section for copyright information will also be displayed, updating automatically to reflect the most current terms and licenses associated with the project.
4. Also would wish to style it by adding some transitions or animations accordingly.

Thank you

**Comment by vansh-codes** [comment]
Go ahead!
Make something appealing as well as chaotic

**Comment by coding-geek-nm** [comment]
yep sure , Thank you .

**Comment by coding-geek-nm** [comment]
@vansh-codes i am pinning the design of the footer . do let me know if any changes .


https://github.com/user-attachments/assets/50c910b2-bf48-414c-b91f-ffc0bdc52421

**Comment by coding-geek-nm** [comment]
sorry This is the revised version. Do let me the changes in the design , so that i can start the implementation.

https://github.com/user-attachments/assets/bfbe7002-b740-435a-a80d-2071fe204d8c

**Comment by vansh-codes** [comment]
Great work! Is it responsive?

**Comment by coding-geek-nm** [comment]
i will make it responsive

**Comment by vansh-codes** [comment]
Sure! Create a PR once its completed

**Comment by coding-geek-nm** [comment]
okay will be done by Tuesday.
