### ISSUE TITLE
Chaotic Feat: Mystery Popups: Popups that appear and disappear at random, leaving users puzzled.

### ISSUE THREAD

**Issue by Ujjwal5705** [vansh-codes/ChaosWeb#60]
### Describe your chaotic idea

As soon as the user enters the website, a click me button will appear upon clicking two options: "Close" and "Open (Don't worry, no virus 😅)." If the user clicks "Open," an image of a monkey with its tongue out will be displayed. If they click "Close," an emotional meme sound will play. This process will repeat every time the user clicks on the "About Us" section.

i would like to contribute to this feature under gssoc-ext (level1,2,3) , hacktoberfest tag.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Wow great idea, can you do this in React?
Currently we are migrating to react 
Check #53

So afterwards would you like to implement this in React ??

**Comment by Ujjwal5705** [comment]
@vansh-codes Yes i can implement this in React

**Comment by vansh-codes** [comment]
I will notify you once the website is completely migrated to React then you start implementing

**Comment by Ujjwal5705** [comment]
Sure! I'll be ready to start implementing the required features.

**Comment by vansh-codes** [comment]
https://github.com/vansh-codes/ChaosWeb/tree/main/chaosweb-v%402

If you are interested you can let me know and start working on it, heres the link to react folder

**Comment by vansh-codes** [comment]
@Ujjwal5705 Are you interested in doing this??

**Comment by Ujjwal5705** [comment]
@vansh-codes Yes, I am interested, started working on this feature

**Comment by vansh-codes** [comment]
Sure go ahead 🚀

**Comment by vansh-codes** [comment]
You will do it in React right? @Ujjwal5705 

React website is in folder named [chaosweb-v@2](https://github.com/vansh-codes/ChaosWeb/tree/main/chaosweb-v%402)

**Comment by Ujjwal5705** [comment]
@vansh-codes yes, but I am not able to fork the new repository.

**Comment by vansh-codes** [comment]
Repository is the same, just a new folder is added
You can pull it if you had it forked and cloned earlier!

**Comment by Ujjwal5705** [comment]
Ok got it. Thank you !
