### ISSUE TITLE
Chaotic Feat: adding a gradient moving background

### ISSUE THREAD

**Issue by bhaviya18** [vansh-codes/ChaosWeb#63]
### Describe your chaotic idea

By adding a gradient moving background everything will be more confusing and chaotic.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/94b59ec8-0147-4bbc-abba-545ab7f61228)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Completed
