### ISSUE TITLE
Adding feedabck button 

### ISSUE THREAD

**Issue by Aditijainnn** [vansh-codes/ChaosWeb#67]
### Describe your chaotic idea

![image](https://github.com/user-attachments/assets/e71d8c1c-8a39-4195-a123-f3f82573e282)
in this adding feedback/rate us option also

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/39960227-e5f7-467e-8ca6-f97e10c3d90e)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by arpit74170** [comment]
Assign this task to me i will add the button with a ui and color version

**Comment by vansh-codes** [comment]
Its not required, closing this issue!
