### ISSUE TITLE
Documentation Chaos: Making a better sign up page

### ISSUE THREAD

**Issue by Adrija05** [vansh-codes/ChaosWeb#68]
### Describe the Documentation Update

Issue: Currently, the "Sign-Up" page is unresponsive when clicked, and nothing is being displayed. This is a critical functionality for user , and a non-working sign-up page can lead to loss of potential users.
Proposed Solution: I would like to fix this issue by ensuring that the "Sign-Up" page loads correctly and functions smoothly. Additionally, I plan to redesign the page to make it more user-friendly and visually appealing.

### Add References or Examples

<img width="256" alt="Screenshot 2024-10-09 at 8 52 26 PM" src="https://github.com/user-attachments/assets/409fe807-f526-4441-89fc-5d6c7305bfc7">

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Migrating to React, check #53

**Comment by vansh-codes** [comment]
Actually migrating to React so no need to work on current codebase, you can propose your ideas when we completely migrateto React and #53 is closed

**Comment by vansh-codes** [comment]
https://github.com/vansh-codes/ChaosWeb/tree/main/chaosweb-v%402

If you are interested you can let me know and start working on it, heres the link to react folder

**Comment by sameer-soni** [comment]
@vansh-codes yes I'm. Can you add the the label of gssoc/hactoberfest and assign me this issue?

**Comment by vansh-codes** [comment]
@Adrija05 Are you interested or shall I assign it to @sameer-soni  ??
Please respond withing 24hours

**Comment by sameer-soni** [comment]
@vansh-codes yes I am. if this issue comes under hacktoberfest-accepted and gssoc.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by Adrija05** [comment]
Yes I will be working on it

**Comment by vansh-codes** [comment]
Are you working on it or no @Adrija05  ??
