### ISSUE TITLE
Chaotic Feat: Wonky sounds!

### ISSUE THREAD

**Issue by codingkatty** [vansh-codes/ChaosWeb#7]
### Describe your chaotic idea

To add to the chaos, we need noise! My idea is to add a sound effect whenever the mouse is clicked or a key is pressed. Noises are pretty much just farm noises (eg. chicken, cow, cat, etc), or wonky noises. There's many noises and its basically just random each time. (btw this is my first time doin this sry if I get anything wrong!! > <)

### Add Screenshots or Sketches

I havent got any :/ But I searched up it, sounds can autoplay if the user interacts (eg click), haven't tested it but I chose to believe it haha.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Great idea! I have some tips for you on this
1. add a separate js folder and add the script.js (dont forget to update the route) and create new js file for sound named sound.js and create function to play sound so we can import it and use it on any page
2. the random sound shouldnt occur on clicking anywhere on the page, it should occur on clicking buttons only, like on navbar, or other buttons

All the best 🚀
Happy coding!

**Comment by vansh-codes** [comment]
Completed ✅
