### ISSUE TITLE
Chaotic Feat: Update Circle Icon in Browser Tab for 'ChaosWeb - The Disorderly UI

### ISSUE THREAD

**Issue by T-Fathima** [vansh-codes/ChaosWeb#71]
### Describe your chaotic idea

The current circle icon (globe icon) displayed in the browser tab for "ChaosWeb - The Disorderly UI" is a placeholder. We should replace this with a custom favicon that represents the application.
Proposed Solution:
Design and upload a custom favicon that reflects the application's identity and replace the current icon.

I would like to work on this.
@vansh-codes Please assign it to me under gssoc-ext and hacktoberfest 

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/265fb50c-93c6-4a71-ab44-1b15e2177375)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
GO ahead 💯

**Comment by vansh-codes** [comment]
Completed 👍
