### ISSUE TITLE
CHAOS REPORT: Logo beside title is not properly rendered

### ISSUE THREAD

**Issue by T-Fathima** [vansh-codes/ChaosWeb#72]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

The image is not properly rendered 
I would like to work on this issue
@vansh-codes Please assign it to me under gssoc-ext and hacktoberfest.
![image](https://github.com/user-attachments/assets/31830168-0784-487f-83ea-eddd9056a41b)

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead 👍
