### ISSUE TITLE
I want to add a new properly aligned, attractive and eye-catching logo in ChaosWeb.

### ISSUE THREAD

**Issue by MimanshaKaur** [vansh-codes/ChaosWeb#74]
![Screenshot 2024-10-10 184438](https://github.com/user-attachments/assets/91c0001a-e0e3-408f-a939-3a17927bb93c)

 As it can seen that the logo image is not supporting so in order to  resolve this issue and make this project more impressive i want to add an attractive and eye- catching logo related to the theme of this project. 

- I will design this logo by my own and will add on it.
- Also, there is some alignment and spacing issue around the previous logo , so i will work on it and resolve it.

**Comment by vansh-codes** [comment]
Go ahead 🚀  Make a better logo

**Comment by vansh-codes** [comment]
Please use Issue templates to create issue from the next time

**Comment by vansh-codes** [comment]
Logo is already fixed, you can check it once and then continue working

**Comment by MimanshaKaur** [comment]
ok

**Comment by MimanshaKaur** [comment]
![Screenshot 2024-10-10 194447](https://github.com/user-attachments/assets/3d2aa318-ba6c-4ca2-a216-95cacc2d46eb)
 i have seen this but still the black text around the logo is not that much clearly visible on the dark background..so i will create one and add👍

**Comment by vansh-codes** [comment]
Okay sure 👍

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by MimanshaKaur** [comment]
Hii @vansh-codes  i have designed 2 logos for chaosweb. please have a look and suggest which one is better!

**Present Logo:**
![Screenshot 2024-10-15 141241](https://github.com/user-attachments/assets/7dba39ff-f990-4d31-af65-c4feb4099315)


**New Logo: (1)**
![Screenshot 2024-10-15 140156](https://github.com/user-attachments/assets/d7217e97-5564-479e-9076-4faa4b9ed2d4)

**New Logo: (2)**
![Screenshot 2024-10-15 140926](https://github.com/user-attachments/assets/4934c33c-39ea-4462-84dd-e5296fcfc21e)


I Think The First one that i have created is going better with chaotic theme.

**Comment by vansh-codes** [comment]
Wow cool! Yup 1st one seems chaotic! 😵‍💫🫨

**Comment by MimanshaKaur** [comment]
Thank You @vansh-codes
