### ISSUE TITLE
Chaotic Feat: Adding vibrant color elements and Changing heading's font style and background to make it more chaotic.

### ISSUE THREAD

**Issue by MimanshaKaur** [vansh-codes/ChaosWeb#75]
### Describe your chaotic idea

![Screenshot 2024-10-10 190702](https://github.com/user-attachments/assets/825620f6-563b-418d-8900-b7a463a6f0dd)

To make ChaosWeb even messier or more unpredictable :
- I want to add some changes in the background at the top of the page.
- i want to add some bubble shaped elements or some random letters or images of vibrant colors that will float on the screen along with already added images .
- Also, i want to use little bit confusing or messy type of font style for this heading with bright font- color which will actually relate to our ChoasWeb theme. Also, i want to adjust the spacing and indentation as well.

@vansh-codes Please give me the chance to work on this issue with labels of gssoc-ext and hacktoberfest-accepted.

### Add Screenshots or Sketches

![Screenshot 2024-10-10 191939](https://github.com/user-attachments/assets/9967ca63-bad3-47cb-9592-780f980d9991)

Like this , i want to add this type of design on the top . i will just shift the heading little bit down and add this above the project name. it will surely give a messy but impressive look to your project.

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead

**Comment by MimanshaKaur** [comment]
Thankyou so much @vansh-codes 
Can you please add level 2 or 3 for this task? As i have to work on overall designing for this

**Comment by MimanshaKaur** [comment]
@vansh-codes  i was working on this project ..but when i am running your project through deployment link ..the background is gradient in color

![Screenshot 2024-10-11 154123](https://github.com/user-attachments/assets/c96bb5c7-0cf0-4ed3-8cc5-2719076ca390)


but when i fork the repo in my github and clone this repo ..the background is still black.
see..👇👇
![Screenshot 2024-10-11 154034](https://github.com/user-attachments/assets/5999b65e-2f9a-451d-8e2c-33d7c2940ce4)

**Comment by vansh-codes** [comment]
Hey @MimanshaKaur 
You are working on the react folder or the html css ??
For react the deployment is https://chaosweb.vercel.app
For html css the deployment link is: https://vansh-codes.github.io/ChaosWeb/

The React project still has black background which has to be updated, and i guess you cloned and ran the react project using npm run dev thats why you see the black background, if you will open the html file in the root directory then you will be able to see the colorful gradient

**Comment by vansh-codes** [comment]
I hope you understood
Can you do this task in React? as I will be removing the html,css,js and entirely migrating to React so it would be better if you can do this task in React ?
Let me know if you can do it in React

**Comment by MimanshaKaur** [comment]
ok @vansh-codes 
its black in mine...then it means i am already working in React.

so, no issues, i will make changes in that react one only ..in which i am already working👍
Yeah it will be better if you remove that html ,css one ..bcz its causing confusion.

**Comment by MimanshaKaur** [comment]
@vansh-codes i am done with my task but before showing it to you.. one more idea came to my mind ...can i change its background as well.. from normal black to some dark gradient shades...????

**Comment by vansh-codes** [comment]
Done
