### ISSUE TITLE
Chaotic Feat: Introducing Chaotic Interactions on Website Load

### ISSUE THREAD

**Issue by HarshitShukla-dev** [vansh-codes/ChaosWeb#79]
### Describe your chaotic idea

Currently, the website presents a static and predictable homepage. To enhance user engagement and create a more dynamic and chaotic experience, we propose introducing chaotic elements that activate upon user interaction.

Chaotic Idea:
Upon loading the homepage, the website will appear normal and functional. However, once the user interacts with any element (clicks a button, hovers over a link, scrolls the page), the chaos will start.

### Add Screenshots or Sketches

![image](https://github.com/user-attachments/assets/375fcecb-f183-4ee5-a813-be90455f4a90)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
interesting!
