### ISSUE TITLE
Button disappears

### ISSUE THREAD

**Issue by ghost** [vansh-codes/ChaosWeb#8]
### Describe your chaotic idea

The moment you try to click on a button, it moves away or disappears. Users have to chase the button to click it, creating a playful but frustrating experience.

### Add Screenshots or Sketches

it keeps moving over the screen
<img width="486" alt="Screenshot 2024-10-07 at 2 56 11 PM" src="https://github.com/user-attachments/assets/2007a0e6-69fd-415a-9782-8361583af1f7">

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Seems interesting
Wait for #2 to be completed then you can continue with your implementation
till that time search for new issues!
Happy Coding 🚀

**Comment by Rishita-2714** [comment]
I would like to work on this project. please assign it to me.

**Comment by vansh-codes** [comment]
Its already assigned to the creator, waiting for #2 to be completed then I will assign it
You can search for new issues @Rishita-2714  which I will be happy to assign!

**Comment by hana-maria** [comment]
@vansh-codes shall i get started on this?

**Comment by vansh-codes** [comment]
Yes!

**Comment by vansh-codes** [comment]
Is this issue completed?
Please share the PR link if its completed
