### ISSUE TITLE
Chaotic Feat: Laggy Interactions for increased Chaos

### ISSUE THREAD

**Issue by shrashti-19** [vansh-codes/ChaosWeb#82]
### Describe your chaotic idea

Introduce intentional delays in buttons, sliders and other interactive elements. For example, buttons only respond after a 5-second lag, or sliders move at an unpredictable slow speed. This feature amplify user frustration and confusion, enhancing the chaotic experience of ChaosWeb.

Please assign this task to me  @vansh-codes 

### Add Screenshots or Sketches

![Screenshot 2024-10-11 124616](https://github.com/user-attachments/assets/edc81c7a-2e02-4485-9dba-fdf53e23b6d5)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Heyy @shrashti-19 , Can you do this task in react ??
We have created a new folder named 'chaosweb-v@2' for react, are you interested in doing it in React please let me know??

**Comment by shrashti-19** [comment]
Yes, I can do in react.

**Comment by vansh-codes** [comment]
Sure go ahead and do it in React
Folder: `chaosweb-v@2`

**Comment by shrashti-19** [comment]
Okay, I'll do that by tomorrow morning.
