### ISSUE TITLE
Chaotic Feat: Make contact us page more chaotic

### ISSUE THREAD

**Issue by Jay-1409** [vansh-codes/ChaosWeb#83]
### Describe your chaotic idea

The idea is simple i want to make the contact us page more chaotic.
- Make the contact us card rotate when we bring cursor on it and it jumps here and there.
- When submit presset it should bounce and make a sequence of bounces before coming back to its original state
- after successful submit the page redirects to the timeline page.

### Add Screenshots or Sketches

![Uploading image.png…]()
You see its so simple 
lets make it crazy chaotic

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
If the contact page will rotate and bounce then how will the user enter data and press submit??

**Comment by Jay-1409** [comment]
I mean to make it analogous to the home page in which the boxes are moving but are clickable so once you click on it becomes stable.

**Comment by Jay-1409** [comment]
I mean to make it analogous to the home page in which the boxes are moving but are clickable so once you click on it becomes stable.

**Comment by vansh-codes** [comment]
Can you do this task in React ??
We have migrated to React, check folder
`chaosweb-v@2`

**Comment by Jay-1409** [comment]
Yes I can do it on react

**Comment by vansh-codes** [comment]
Go ahead with it!

**Comment by Jay-1409** [comment]
Okayy

**Comment by Jay-1409** [comment]
@vansh-codes 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/838a7e48-3af9-4f76-b414-0ecf417489b5">
 something like this works ?

**Comment by vansh-codes** [comment]
Share a video, cant understand it from screenshot

**Comment by Jay-1409** [comment]
> Share a video, cant understand it from screenshot

um ok, but I had just aligned the things that were not alignes as asked in #85 
ill share a video if u insist.

**Comment by Jay-1409** [comment]
https://github.com/user-attachments/assets/3160840e-1e91-4eb4-80d1-f0182c8b83e6

@vansh-codes  do you want me to add any other animations ?

**Comment by vansh-codes** [comment]
Yes alignment is okay

**Comment by Jay-1409** [comment]
> Yes alignment is okay

should i add any animations ?

**Comment by Jay-1409** [comment]
should i make the PR? @vansh-codes

**Comment by vansh-codes** [comment]
Your task was to make it chaotic right? Bounce and all those animations which you have told in the issue description and you have worked on some other issue alignment? Why?

**Comment by vansh-codes** [comment]
Make the contact page rotate when we bring cursor and all those which you mentioned in the issue? Where is that work? If you did it then share a video of that

**Comment by Jay-1409** [comment]
> Yes I can do it on react

above this u tagged some other issue.

**Comment by Jay-1409** [comment]
so i thought u wanted that work first.

**Comment by Jay-1409** [comment]
i am working on making the page more chaotic now.

**Comment by Jay-1409** [comment]
@vansh-codes  sorry for the late work here is what I did 

Uploading 12.10.2024_00.04.07_REC.mp4…

do you need anychanges?

**Comment by vansh-codes** [comment]
Recording is not available @Jay-1409 
When you upload a video, please wait till its uploaded, I cant see the video, please share again

**Comment by Jay-1409** [comment]
> Recording is not available @Jay-1409 When you upload a video, please wait till its uploaded, I cant see the video, please share again


https://github.com/user-attachments/assets/6ce6c274-4ef3-4b75-a0c0-082dbdb77612

@vansh-codes
