### ISSUE TITLE
Misalignment in the Top Section of the Page of the First Page.

### ISSUE THREAD

**Issue by ansiace** [vansh-codes/ChaosWeb#86]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

The **top section** of the page lacks proper alignment, causing the elements to appear **disorganized** and out of place. This misalignment affects the overall design and gives the page an unstructured look.

### Expected Behavior:
- The elements in the **top section** should be **properly aligned** to create a clean and well-organized layout.
- This would enhance the visual appeal and provide a more professional appearance to the page.

### Current Behavior:
- The elements in the top section are **not aligned properly**, leading to a cluttered and uneven layout.
- This misalignment negatively impacts the user experience and the overall structure of the page.

### Suggested Improvement:
- Adjust the **alignment** of all elements in the top section, ensuring that they are evenly distributed and aligned with each other.
- Consistent **margins, padding**, and **grid structure** could be used to create a balanced layout.

![Screenshot 2024-10-11 194542](https://github.com/user-attachments/assets/5aace4c9-3df4-4f6a-ad6b-6b5e6f2e4dee)

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead

**Comment by vansh-codes** [comment]
You want to fix this in React version right??
