### ISSUE TITLE
Chaotic Feat: I want to change the colours of the page and font families

### ISSUE THREAD

**Issue by ShaliniKashyap717** [vansh-codes/ChaosWeb#89]
### Describe your chaotic idea

with my knowlege of colour palletes, i believe i will give the website far better colours resulting in eye catching impression from the user. present font families and colours are not really pleasant  and the box around the emoji doesnt look good. also the white border around the components doesnt look good. let me make some changes in the css and make the website look more chaotic :) kindly assign it to me under gssoc-ext and hacktoberfest-accepted. i would love to do it for u.

### Add Screenshots or Sketches

<img width="928" alt="Screenshot 2024-10-12 043736" src="https://github.com/user-attachments/assets/dbe024ee-e493-4e1c-831a-4aad36c171b0">

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
You want to work on this in the React folder right?

**Comment by ShaliniKashyap717** [comment]
Yes

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me.

**Comment by vansh-codes** [comment]
GO ahead @manastiwari99
