### ISSUE TITLE
Time-Reactive UI

### ISSUE THREAD

**Issue by hana-maria** [vansh-codes/ChaosWeb#9]
### Describe your chaotic idea

- Create an interface that reacts differently based on the time of day. For example, clicking on “Contact Us” at 2 AM redirects users to a page that says “Too late to reach us. Come back during daylight.”
- Moon which winks when u hover over it

### Add Screenshots or Sketches

<img width="204" alt="Screenshot 2024-10-07 at 3 39 24 PM" src="https://github.com/user-attachments/assets/caae0f24-ed4b-490c-a983-96c5e326ed47">

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Wow seems amazing good job ✨
Wait for #2 to be completed then you can start working on this!
Once again its a really good idea
Thanks!
Happy Coding ✨

**Comment by hana-maria** [comment]
@vansh-codes  Thank youu! Ping me when you want me to start with it : )

**Comment by vansh-codes** [comment]
Sure! 🚀

**Comment by vansh-codes** [comment]
@hana-maria You can start working on this
Make sure to make it reusable in other piece of code as well
