### ISSUE TITLE
Updating vertical scrollbar.

### ISSUE THREAD

**Issue by Tanushree084** [vansh-codes/ChaosWeb#91]
### Describe your chaotic idea

Hey @vansh-codes ,
 I  want to update the vertical scrollbar.
<img width="37" alt="image" src="https://github.com/user-attachments/assets/2bb64360-dbe8-423f-8459-31e6a710f97c">

Can you please assign me this issue ?

### Add Screenshots or Sketches

<img width="37" alt="image" src="https://github.com/user-attachments/assets/72685889-78f2-45a6-a399-d1357c01ccb7">

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead!
