### ISSUE TITLE
Documentation Chaos: Readme more animated

### ISSUE THREAD

**Issue by eshalshaikh07** [vansh-codes/ChaosWeb#93]
### Describe the Documentation Update

A visually appealing README is crucial because it serves as the first impression of the project. It enhances user engagement, making it easier for newcomers to understand the project's purpose and functionalities. By incorporating visual elements like GIFs and diagrams, we can simplify complex concepts, provide clear instructions, and ultimately encourage more users to explore and contribute to the project.

Hi,

I hope this message finds you well. I’m eager to contribute to the project and would love to take on the task of enhancing the README. I have already successfully completed one README task, where I made it more interactive and visually appealing by adding GIFs to demonstrate key features.

Please let me know if you can assign this task to me. I’m looking forward to your feedback and am excited to contribute further!

Thank you!

Best regards,
Eshal :)

### Add References or Examples

https://github.com/eshalshaikh07/Object_tracking_in_360_video/blob/main/README.md reernce i have done 2 readme updations before!

### Confirm

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Okay go ahead!

**Comment by eshalshaikh07** [comment]
assign it to me!

**Comment by eshalshaikh07** [comment]
https://github.com/eshalshaikh07/ChaosWeb/blob/main/README.md done please check!
