### ISSUE TITLE
🔐 Missing `SECURITY.md` File

### ISSUE THREAD

**Issue by azfar-2** [vansh-codes/ChaosWeb#96]
## **Description:**
The repository is currently missing a `SECURITY.md` file, which is essential for outlining security policies and providing guidelines on how to report vulnerabilities. 🛡️

## **Why is this important?**  
- 📜 A `SECURITY.md` file helps contributors and users understand the process for reporting potential security vulnerabilities, which is crucial for keeping the project safe.  
- 🛠️ It builds trust in the project and promotes responsible disclosure, ensuring security concerns are handled properly and promptly.  
- 🚀 Many open-source projects follow this best practice, and having one here would be a valuable addition, especially during Hacktoberfest where contributions are encouraged, and security is key! 🔐

## **Proposed Solution:**  
I would love to help by creating a `SECURITY.md` file that includes:  
- 📝 Clear instructions on how to report vulnerabilities.  
- 📧 Contact details for maintainers (e.g., an email address or a link to a reporting platform).  
- ⚙️ Optional: Additional security guidelines or policies specific to this project.

## Screenshots

![{37E064F3-13BA-4257-B62E-A5B0C18BF218}](https://github.com/user-attachments/assets/4c19ea72-23e9-4ea9-8860-c6dbafb85bb4)

<br>

![{45970F08-E3D1-4278-94E8-A7BD84DEABC2}](https://github.com/user-attachments/assets/ffb7a16c-aedb-4f12-9b65-039baed6229b)

@vansh-codes It would be great if you could assign this issue to me! I'd be happy to contribute and improve the security aspect of this awesome repository. 😊

**If you really need this file, then assign it to me; otherwise, you can close the issue directly. No problem.**

- ***Thank you!***

## Acknowledged 

- [X] I understand that my update will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this documentation update
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
Go ahead ✅
