### ISSUE TITLE
CHAOS REPORT:The sign-up and sign-in

### ISSUE THREAD

**Issue by Bhumika-00** [vansh-codes/ChaosWeb#97]
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

The signin and sign-up page are not opening when we click to them.

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by sayanp607** [comment]
@vansh-codes  brother , please assign this task to me. I have already made many sign up and login pages for different projects and quite experienced in it. I assure the ui of the pages will must be chaotic and  give anti-user experience. I have mentioned you about this issue earlier days, but maybe there exits same issue , so mine was closed that time.

**Comment by Bhumika-00** [comment]
I want the same issue
