### ISSUE TITLE
Chaotic Feat:The ui of contact us page 

### ISSUE THREAD

**Issue by Bhumika-00** [vansh-codes/ChaosWeb#98]
### Describe your chaotic idea

I want to make it more funky that the box is continuously moving in the space. 
Also the submit button is not properly aligned it needs to have a smaller size 
![Screenshot_2024-10-13-11-56-56-443_com android chrome](https://github.com/user-attachments/assets/06c77129-6d3c-4cff-b8f5-dff6a188d9fe)

### Add Screenshots or Sketches

My idea is to make the box continuously moving into the space.
![Screenshot_2024-10-13-11-56-56-443_com android chrome](https://github.com/user-attachments/assets/c2597b05-deea-44c0-b6ac-2d8b22a86a2b)

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by Bhumika-00** [comment]
I accept the assignment.

**Comment by Bhumika-00** [comment]
Please assign this issue a level

**Comment by vansh-codes** [comment]
Level will be assigned on your PR depending on your works complexity
