### ISSUE TITLE
Visible Scrollbars Affecting Website Aesthetics

### ISSUE THREAD

**Issue by diwakarchaurasiya** [vansh-codes/ChaosWeb#99]
### Description:
Both vertical and horizontal scrollbars are visible, negatively impacting the overall aesthetics of the website. Their presence disrupts the clean and polished look of the design.

### Proposed Solution:
Hide the scrollbars to improve visual appeal and create a smoother, more modern browsing experience.

![Screenshot 2024-10-13 143131](https://github.com/user-attachments/assets/b443fb42-9292-43c7-98a3-bb8d75e47bd2)

**Comment by vansh-codes** [comment]
GO ahead

**Comment by diwakarchaurasiya** [comment]
thanks for assigning me this.I will create a pull request as soon as possible.

**Comment by vansh-codes** [comment]
I will assign level after seeing the PR so I can understand your compliexity of work and assign appropriate level label

**Comment by BaniSinghgithub** [comment]
hello sir @vansh-codes , pls assign me this task.

**Comment by vansh-codes** [comment]
@diwakarchaurasiya any updates?

**Comment by diwakarchaurasiya** [comment]
yes,i will raise pull request by today  evening ,

**Comment by vansh-codes** [comment]
@diwakarchaurasiya whats the update??
